Repository daviseford/aos-reminders, pull requests merged in 2019-10, with the labels that each got.

#497 Allegiance/unit abilities are auto-selected (fixes #378)
  package.json
  src/army/daughters_of_khaine/artifacts.ts
  src/army/daughters_of_khaine/traits.ts
  src/army/legion_of_sacrament/traits.ts
  src/army/legions_of_azgorh/traits.ts
  src/army/legions_of_nagash/traits.ts
  src/army/lethisian_army/artifacts.ts
  src/army/nurgle/traits.ts
  src/components/helpers/spinner.tsx
  src/components/input/army_builder.tsx
  src/components/input/army_builder_cards.ts
  src/components/input/getSideEffects.ts
  src/components/input/savedArmies/save_army_btn.tsx
  src/components/input/savedArmies/save_army_modal.tsx
  src/components/input/savedArmies/show_saved_armies_btn.tsx
  src/components/input/savedArmies/update_name_modal.tsx
  src/components/input/toolbar/toolbar.tsx
  src/components/print/pdfModal.tsx
  src/css/theme.scss
  src/ducks/realmscape.ts
  src/ducks/selections.ts
  src/types/selections.ts
  src/types/store.ts
  src/utils/textUtils.ts
  src/utils/withSelect.ts
  upload.sh
  yarn.lock
Labels: enhancement

#498 Typos in Bonesplitterz allegiance abilities
  src/army/bonesplitterz/abilities.ts
  src/army/generic/realmscape_commands.ts
  src/army/generic/scenery.ts
Labels: rule updates

#499 Fix for when Gotrek is imported as an ally
  src/army/grand_alliances/order/units.ts
  src/utils/getArmy/getAllyArmyUnits.ts
Labels: bug

#500 Update react-select dependency
  package.json
  yarn.lock
Labels: maintenance

#504 Typos and translations
  src/tests/azyrImport.test.ts
  src/tests/fixtures/azyr/json/DoK2.json
  src/tests/fixtures/azyr/pdf/DoK2.pdf
  src/utils/azyr/azyrPdf.ts
  src/utils/import/options.ts
Labels: rule updates

#506 Fixing #505
  src/army/gloomspite/units.ts
Labels: rule updates

#507 Better handling for expired users (fixes #501, fixes #503)
  src/components/input/cancellation_modal.tsx
  src/components/input/savedArmies/save_army_btn.tsx
  src/components/input/toolbar/toolbar.tsx
  src/components/page/navbar.tsx
  src/components/routes/Profile.tsx
  src/components/routes/Subscribe.tsx
  src/context/useSubscription.tsx
  src/utils/subscriptionUtils.ts
Labels: enhancement, subscriber feature, ui

#512 The Great waagh
  src/army/da_great_waaagh/abilities.ts
  src/army/da_great_waaagh/artifacts.ts
  src/army/da_great_waaagh/index.ts
  src/army/da_great_waaagh/spells.ts
  src/army/da_great_waaagh/traits.ts
  src/army/da_great_waaagh/units.ts
  src/meta/army_list.ts
  src/meta/factions.ts
  src/utils/armyUtils.ts
Labels: new army, rule updates

#513 Update dependencies
  package.json
  yarn.lock
Labels: maintenance

#515 Fix Morathi import and reenable test
  src/tests/azyrImport.test.ts
  src/tests/getAzyrArmy.test.ts
  src/utils/azyr/azyrPdf.ts
Labels: azyr, bug

#518 Add Korghos Khul typo mapping
  src/utils/import/options.ts
Labels: warscroll-builder

#519 Comma fix (fixes #516)
  src/types/data.ts
  src/utils/processReminders.ts
  src/utils/textUtils.ts
Labels: bug

#520 Favorite armies (fixes #352)
  package.json
  public/img/logo_more_padding.png
  src/api/subscriptionApi.ts
  src/components/input/select.tsx
  src/components/page/homeHeader.tsx
  src/components/page/navbar.tsx
  src/components/routes/Profile.tsx
  src/components/routes/Subscribe.tsx
  src/context/useSavedArmies.tsx
  src/context/useSubscription.tsx
  src/types/subscription.ts
  src/utils/env.ts
  src/utils/localStore.ts
  yarn.lock
Labels: api, enhancement, subscriber feature, ui

#521 Title case failed imports
  src/utils/analytics.ts
  src/utils/import/options.ts
Labels: bug

#522 Add Nighthaunt Endless Spells to all Nagash-affiliated armies
  src/army/grand_host_of_nagash/endless_spells.ts
  src/army/grand_host_of_nagash/index.ts
  src/army/legion_of_blood/endless_spells.ts
  src/army/legion_of_blood/index.ts
  src/army/legion_of_night/endless_spells.ts
  src/army/legion_of_night/index.ts
  src/army/legion_of_sacrament/endless_spells.ts
  src/army/legion_of_sacrament/index.ts
  src/army/legions_of_azgorh/endless_spells.ts
  src/army/legions_of_azgorh/index.ts
  src/army/legions_of_grief/endless_spells.ts
  src/army/legions_of_grief/index.ts
  src/army/legions_of_nagash/endless_spells.ts
  src/army/legions_of_nagash/index.ts
  src/army/legions_of_nagash/units.ts
  src/army/nighthaunt/endless_spells.ts
  src/army/nighthaunt/units.ts
Labels: azyr, warscroll-builder

#527 Added spells for Eidolon and Tidecaster (fixes #524)
  src/army/idoneth/units.ts
Labels: rule updates

#529 Improved WSB Import
  src/tests/warscrollImport.test.ts
  src/utils/import/options.ts
  src/utils/warscroll/getWarscrollArmy.ts
Labels: warscroll-builder

#537 Add a Notification Banner for CoS/Orruks
  src/components/info/notification_banner.tsx
  src/components/routes/Home.tsx
  src/utils/localStore.ts
Labels: ui

#538 Add soul grinder
  src/army/grand_alliances/chaos/units.ts
Labels: rule updates

#539 Add Be'lakor
  src/army/grand_alliances/chaos/units.ts
Labels: rule updates

#540 Updates to Links and Banners
  package.json
  src/components/helpers/link.tsx
  src/components/info/banners/orruk_cos_banner.tsx
  src/components/info/donate.tsx
  src/components/info/notification_banner.tsx
  src/components/input/importPdf/drop_container.tsx
  src/components/page/contact.tsx
  src/components/page/homeHeader.tsx
  src/components/routes/Home.tsx
  src/components/routes/Subscribe.tsx
  src/utils/env.ts
  yarn.lock
Labels: ui

#542 Add GA events with factionNames
  src/components/input/savedArmies/delete_army_modal.tsx
  src/components/input/savedArmies/load_army_btn.tsx
  src/components/input/savedArmies/save_army_modal.tsx
  src/components/input/savedArmies/saved_army_card.tsx
  src/components/input/savedArmies/update_army_btn.tsx
Labels: maintenance

#543 Orruk Warclans - Bonesplitterz & Big Waagh
  src/army/big_waaagh/abilities.ts
  src/army/bonesplitterz/abilities.ts
  src/army/bonesplitterz/allegiances.ts
  src/army/bonesplitterz/artifacts.ts
  src/army/bonesplitterz/index.ts
  src/army/bonesplitterz/spells.ts
  src/army/bonesplitterz/traits.ts
  src/army/bonesplitterz/units.ts
Labels: new army, rule updates

#544 Condense PDF Formatting (fixes #496)
  src/utils/pdf/generate/generatePdf.ts
Labels: pdf

#545 Rearrange Subscribe page
  src/components/print/pdfModal.tsx
  src/components/routes/Profile.tsx
  src/components/routes/Subscribe.tsx
  src/utils/textUtils.ts
Labels: ui

#534 Orruk Warclans - Ironjawz
  src/army/ironjawz/abilities.ts
  src/army/ironjawz/allegiances.ts
  src/army/ironjawz/artifacts.ts
  src/army/ironjawz/index.ts
  src/army/ironjawz/spells.ts
  src/army/ironjawz/traits.ts
  src/army/ironjawz/units.ts
  src/components/info/banners/app_banner.tsx
  src/components/info/banners/notification_banner.tsx
  src/components/info/banners/orruk_cos_banner.tsx
  src/components/routes/Home.tsx
Labels: new army, rule updates

#547 Moved FEC delusions to allegiances
  src/army/flesh_eater_courts/allegiances.ts
  src/army/flesh_eater_courts/traits.ts
  src/army/ironjawz/units.ts
Labels: rule updates

#548 Remove AppBanner from Home
  package.json
  src/components/info/banners/app_banner.tsx
  src/components/routes/Home.tsx
  src/tests/getAzyrArmy.test.ts
  src/tests/warscrollImport.test.ts
Labels: ui

#550 Add CoS to Import options (fixes #549)
  src/army/cities_of_sigmar/units.ts
  src/tests/azyrImport.test.ts
  src/tests/fixtures/azyr/json/CoS1.json
  src/tests/getAzyrArmy.test.ts
  src/utils/azyr/azyrPdf.ts
  src/utils/import/options.ts
Labels: azyr, warscroll-builder

#552 Update CoS units.ts
  src/army/cities_of_sigmar/units.ts
Labels: rule updates

#553 CoS Generals
  src/army/cities_of_sigmar/units.ts
  src/tests/azyrImport.test.ts
  src/tests/fixtures/azyr/json/CoS1.json
  src/tests/fixtures/azyr/json/CoS2.json
  src/tests/fixtures/azyr/json/CoS3.json
  src/tests/getAzyrArmy.test.ts
  src/utils/azyr/azyrPdf.ts
Labels: azyr

#554 More CoS fixes (Battle Traits, typos)
  src/army/cities_of_sigmar/traits.ts
  src/army/cities_of_sigmar/units.ts
  src/tests/azyrImport.test.ts
  src/tests/fixtures/azyr/json/CoS4.json
  src/tests/getAzyrArmy.test.ts
  src/utils/azyr/azyrPdf.ts
Labels: azyr, rule updates

#555 Update deps
  package.json
  yarn.lock
Labels: maintenance

#556 Remove negative lookbehind
  src/utils/azyr/azyrPdf.ts
Labels: azyr

#559 Switched Tzaangors to pull from BoC
  src/army/beasts_of_chaos/units.ts
  src/army/tzeentch/units.ts
Labels: rule updates

#565 Handle complex CoS WSB imports
  src/army/ironjawz/allegiances.ts
  src/tests/warscrollImport.test.ts
  src/utils/import/index.ts
  src/utils/import/options.ts
  src/utils/warscroll/getWarscrollArmy.ts
Labels: warscroll-builder

#567 Some minor import fixes
  src/army/big_waaagh/traits.ts
  src/army/bonesplitterz/allegiances.ts
  src/army/skaven/units.ts
  src/army/stormcast_eternals/units.ts
  src/tests/warscrollImport.test.ts
  src/utils/getArmy/getCollection.ts
  src/utils/import/options.ts
Labels: azyr, warscroll-builder

#568 Switch to passing userName instead of subscriptionId to cancel
  src/api/subscriptionApi.ts
  src/components/routes/Subscribe.tsx
  src/context/useSubscription.tsx
Labels: api

#569 Fix trait typos for imports
  src/army/ironjawz/traits.ts
  src/army/legion_of_blood/traits.ts
  src/army/legions_of_nagash/traits.ts
Labels: rule updates

#571 Better subscription cancellation and remove Lore of Leaves
  src/api/subscriptionApi.ts
  src/context/useSubscription.tsx
  src/utils/warscroll/getWarscrollArmy.ts
Labels: api, warscroll-builder

#572 Copy error files to S3 (fixes #514)
  package.json
  src/api/preferenceApi.ts
  src/components/input/importPdf/parseFile.ts
  src/utils/import/warnings.ts
  src/utils/pdf/pdfUtils.ts
  yarn.lock
Labels: api, enhancement

#574 First batch of import fixes
  src/army/flesh_eater_courts/allegiances.ts
  src/army/flesh_eater_courts/spells.ts
  src/army/flesh_eater_courts/traits.ts
  src/tests/azyr/azyrImport.test.ts
  src/tests/azyr/getAzyrArmy.test.ts
  src/tests/fixtures/azyr/json/FEC2.json
  src/tests/fixtures/warscroll/json/1571040089053-Warscroll_Builder.json
  src/tests/fixtures/warscroll/json/1571060674200-Warscroll_Builder.json
  src/tests/warscroll/warscrollJson.test.ts
  src/tests/warscroll/warscrollPdf.test.ts
  src/tests/warscroll/warscrollTxt.test.ts
  src/utils/azyr/azyrPdf.ts
Labels: azyr, bug, warscroll-builder

#578 Fix Bloodlords import from Azyr
  src/tests/azyr/getAzyrArmy.test.ts
  src/tests/fixtures/azyr/json/Khorne2.json
  src/utils/azyr/azyrPdf.ts
Labels: rule updates

#580 Save army when redirecting (fixes #566)
  package.json
  public/img/AoS_Subscribe_Support.gif
  public/img/AoS_Subscribe_Support.mp4
  src/components/App.tsx
  src/components/info/banners/app_banner.tsx
  src/components/input/savedArmies/save_army_btn.tsx
  src/components/page/homeHeader.tsx
  src/components/page/navbar.tsx
  src/components/payment/pricingPlans.tsx
  src/context/useSavedArmies.tsx
  src/css/animations.scss
  src/ducks/army.ts
  src/ducks/factionNames.ts
  src/ducks/realmscape.ts
  src/ducks/selections.ts
  src/ducks/selectors.ts
  src/ducks/visibility.ts
  src/index.tsx
  src/types/store.ts
  src/utils/loadArmyFromLocalStore.ts
  src/utils/localStore.ts
  yarn.lock
Labels: enhancement

#583 Big Waaagh cleanup
  src/army/big_waaagh/abilities.ts
Labels: rule updates

#584 Better Subscription debug log
  src/context/useSubscription.tsx
Labels: bug

#588 Remove .txt import for WSB, add more import tests
  package.json
  src/army/bonesplitterz/units.ts
  src/army/fyreslayers/units.ts
  src/army/grand_alliances/destruction/units.ts
  src/army/ironjawz/units.ts
  src/components/input/importPdf/drop_zone.tsx
  src/components/input/importPdf/parseFile.ts
  src/tests/fixtures/warscroll/json/1571084621521-Warscroll_Builder.json
  src/tests/fixtures/warscroll/json/1571131908806-Warscroll_Builder.json
  src/tests/fixtures/warscroll/json/1571158898802-Warscroll_Builder.json
  src/tests/fixtures/warscroll/json/1571165179317-Warscroll_Builder.json
  src/tests/fixtures/warscroll/json/1571171962804-Warscroll_Builder.json
  src/tests/fixtures/warscroll/txt/OrderMeetingEngagement.txt
  src/tests/fixtures/warscroll/txt/SeraphonMultipleAllies.txt
  src/tests/fixtures/warscroll/txt/SeraphonNoMetadata.txt
  src/tests/fixtures/warscroll/txt/SeraphonWithMetadata.txt
  src/tests/fixtures/warscroll/txt/ShortSummary.txt
  src/tests/warscroll/warscrollJson.test.ts
  src/tests/warscroll/warscrollTxt.test.ts
  src/types/import.ts
  src/utils/import/options.ts
  src/utils/warscroll/getWarscrollArmy.ts
  yarn.lock
Labels: azyr, warscroll-builder

#593 Remove Gordrakk-specific para from Maw-krusha ability
  src/army/ironjawz/units.ts
Labels: rule updates

#594 Warn when attempting to import AoS Reminder PDFs
  src/components/input/importPdf/drop_container.tsx
  src/components/input/importPdf/drop_zone.tsx
  src/components/input/importPdf/parseFile.ts
Labels: ui

#595 Adding for #590 Warboss
  src/army/big_waaagh/units.ts
  src/army/greenskinz/index.ts
  src/army/greenskinz/units.ts
  src/meta/army_list.ts
  src/meta/factions.ts
Labels: new army

#596 Log 100% of GA Page Load times
  package.json
  src/utils/analytics.ts
  yarn.lock
Labels: maintenance

#599 More import fixes and tests
  src/tests/fixtures/warscroll/json/1571263525536-Warscroll_Builder.json
  src/tests/fixtures/warscroll/json/1571285206236-Warscroll_Builder.json
  src/tests/fixtures/warscroll/json/1571287948786-Warscroll_Builder.json
  src/tests/warscroll/warscrollJson.test.ts
  src/tests/warscroll/warscrollPdf.test.ts
  src/utils/import/options.ts
  src/utils/warscroll/getWarscrollArmy.ts
Labels: warscroll-builder

#602 Progressive Web App - adds offline capability (fixes #597)
  public/android-chrome-192x192.png
  public/android-chrome-512x512.png
  public/apple-touch-icon.png
  public/browserconfig.xml
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon.ico
  public/img/logo_medium_padding.png
  public/img/logo_square.png
  public/img/transparent-with-padding.png
  public/index.html
  public/mstile-150x150.png
  public/safari-pinned-tab.svg
  public/site.webmanifest
  src/components/App.tsx
  src/components/helpers/suspenseFallbacks.tsx
  src/components/info/donate.tsx
  src/components/info/offline.tsx
  src/components/input/ally_army_builder.tsx
  src/components/input/importPdf/drop_zone.tsx
  src/components/input/importPdf/parseFile.ts
  src/components/input/savedArmies/load_army_btn.tsx
  src/components/input/savedArmies/loaded_army_header.tsx
  src/components/input/savedArmies/save_army_btn.tsx
  src/components/input/savedArmies/saved_armies.tsx
  src/components/input/savedArmies/saved_army_card.tsx
  src/components/input/savedArmies/show_saved_armies_btn.tsx
  src/components/input/toolbar/toolbar.tsx
  src/components/page/contact.tsx
  src/components/page/footer.tsx
  src/components/page/homeHeader.tsx
  src/components/page/navbar.tsx
  src/components/payment/pricingPlans.tsx
  src/components/print/pdfModal.tsx
  src/components/routes/Profile.tsx
  src/components/routes/Subscribe.tsx
  src/context/useOfflineStatus.tsx
  src/context/useSavedArmies.tsx
  src/context/useSubscription.tsx
  src/index.tsx
  src/serviceWorker.ts
  src/theme/helperClasses.ts
  src/utils/loadArmyFromLocalStore.ts
  src/utils/localStore.ts
Labels: enhancement, subscriber feature

#605 Add fallback ping for offline status
  src/context/useOfflineStatus.tsx
Labels: offline

#609 Don't switch factionName when selections are reset (fixes #607)
  src/components/page/homeHeader.tsx
  src/context/useSavedArmies.tsx
Labels: bug, subscriber feature

#610 Add Update Notification Banner (fixes #608)
  package.json
  src/components/info/banners/update_banner.tsx
  src/components/info/donate.tsx
  src/components/info/offline.tsx
  src/components/input/ally_army_builder.tsx
  src/components/input/importPdf/drop_zone.tsx
  src/components/input/savedArmies/load_army_btn.tsx
  src/components/input/savedArmies/loaded_army_header.tsx
  src/components/input/savedArmies/save_army_btn.tsx
  src/components/input/savedArmies/saved_armies.tsx
  src/components/input/savedArmies/saved_army_card.tsx
  src/components/input/savedArmies/show_saved_armies_btn.tsx
  src/components/input/toolbar/toolbar.tsx
  src/components/page/contact.tsx
  src/components/page/homeHeader.tsx
  src/components/page/navbar.tsx
  src/components/print/pdfModal.tsx
  src/components/routes/Home.tsx
  src/context/useAppStatus.tsx
  src/context/useOfflineStatus.tsx
  src/context/useSavedArmies.tsx
  src/index.tsx
  src/serviceWorker.ts
  src/tests/fixtures/warscroll/json/1571327027143-Warscroll_Builder.json
  src/tests/fixtures/warscroll/json/1571329765256-Warscroll_Builder.json
  src/tests/fixtures/warscroll/json/1571347470427-Warscroll_Builder.json
  src/tests/warscroll/warscrollJson.test.ts
Labels: offline

#611 Add display event
  src/components/info/banners/update_banner.tsx
  src/context/useAppStatus.tsx
  src/utils/analytics.ts
Labels: offline

#618 Offline Sale!
  src/components/App.tsx
  src/components/helpers/suspenseFallbacks.tsx
  src/components/info/banners/app_banner.tsx
  src/components/input/importPdf/drop_container.tsx
  src/components/input/savedArmies/save_army_btn.tsx
  src/components/input/toolbar/import_army_btn.tsx
  src/components/page/navbar.tsx
  src/components/page/navbar_wrapper.tsx
  src/components/payment/plans.ts
  src/components/payment/pricingPlans.tsx
  src/components/routes/Home.tsx
  src/components/routes/Profile.tsx
  src/components/routes/Subscribe.tsx
  src/context/useSubscription.tsx
  src/utils/analytics.ts
  src/utils/env.ts
  src/utils/mapSizesToProps.ts
Labels: ui

#619 Improved parser checks
  src/components/input/importPdf/parseFile.ts
  src/utils/azyr/azyrPdf.ts
Labels: azyr, warscroll-builder

#620 Add more import tests
  src/army/ironjawz/units.ts
  src/tests/fixtures/warscroll/json/1571233444845-Warscroll_Builder.json
  src/tests/fixtures/warscroll/json/1571240331862-Warscroll_Builder.json
  src/tests/fixtures/warscroll/json/1571329765256-Warscroll_Builder.json
  src/tests/fixtures/warscroll/json/1571347470427-Warscroll_Builder.json
  src/tests/fixtures/warscroll/json/1571425644480-Warscroll_Builder.json
  src/tests/warscroll/warscrollJson.test.ts
  src/tests/warscroll/warscrollPdf.test.ts
Labels: rule updates, warscroll-builder

#623 Better ally detection on import, add allied endless spells to Army
  package.json
  src/tests/azyr/getAzyrArmy.test.ts
  src/tests/getArmy.test.ts
  src/tests/warscroll/warscrollJson.test.ts
  src/tests/warscroll/warscrollPdf.test.ts
  src/utils/getArmy/getAllyArmyUnits.ts
  src/utils/getArmy/getArmy.ts
  src/utils/getArmy/getCollection.ts
  src/utils/getArmy/modify.ts
  src/utils/import/allyData.ts
  src/utils/import/index.ts
  yarn.lock
Labels: azyr, enhancement, warscroll-builder

#624 Accessibility
  src/components/helpers/link.tsx
  src/components/input/importPdf/drop_container.tsx
  src/components/page/footer.tsx
  src/components/page/homeHeader.tsx
  src/components/routes/Subscribe.tsx
Labels: ui

#626 Add two import fixes
  src/army/flesh_eater_courts/traits.ts
  src/tests/azyr/azyrImport.test.ts
  src/tests/azyr/getAzyrArmy.test.ts
  src/tests/fixtures/azyr/json/FEC3.json
  src/tests/fixtures/warscroll/json/1571520651334-Warscroll_Builder.json
  src/tests/warscroll/warscrollJson.test.ts
  src/utils/import/options.ts
Labels: azyr, warscroll-builder

#630 Magmic Invocations Reminder
  src/army/fyreslayers/abilities.ts
Labels: rule updates

#637 Errata
  src/army/bonesplitterz/spells.ts
  src/army/cities_of_sigmar/artifacts.ts
  src/army/cities_of_sigmar/traits.ts
  src/army/cities_of_sigmar/units.ts
  src/army/daughters_of_khaine/units.ts
  src/army/greenskinz/units.ts
  src/army/ironjawz/units.ts
  src/army/stormcast_eternals/units.ts
Labels: rule updates

#639 Fix the phases on a couple of Stormcast abilities
  src/army/stormcast_eternals/units.ts
Labels: rule updates

#642 Remove Sale Banner + fix Azyr import typo
  package.json
  src/components/routes/Home.tsx
  src/tests/azyr/azyrImport.test.ts
  src/tests/azyr/getAzyrArmy.test.ts
  src/tests/fixtures/azyr/json/LoG2.json
  src/utils/azyr/azyrPdf.ts
  yarn.lock
Labels: azyr, ui

#644 Check for duplicate entry (fixes #643 )
  package.json
  src/utils/pdf/generate/generatePdf.ts
  yarn.lock
Labels: bug, pdf

#647 2+ Tough bug PDF bug solved :)
  src/army/ironjawz/units.ts
  src/utils/pdf/generate/generatePdf.ts
Labels: bug, pdf

#656 Fixes for #654
  src/army/ironjawz/allegiances.ts
  src/army/ironjawz/traits.ts
Labels: rule updates

#660 Import fixes and Skaven updates (fixes #659)
  src/army/skaven/units.ts
  src/tests/battlescribe/battlescribeHTML.test.ts
  src/tests/fixtures/battlescribe/html/BigWaaagh2.html
  src/tests/fixtures/battlescribe/html/Khorne4.html
  src/tests/warscroll/warscrollPdf.test.ts
  src/utils/azyr/azyrPdf.ts
  src/utils/battlescribe/getters.ts
  src/utils/import/options.ts
Labels: battlescribe, rule updates

#661 Tweaks to hidden reminders + test updates
  package.json
  src/army/skaven/units.ts
  src/components/info/reminder.tsx
  src/tests/battlescribe/battlescribeHTML.test.ts
  src/tests/fixtures/battlescribe/html/Skaven2.html
  src/utils/import/options.ts
  yarn.lock
Labels: battlescribe, rule updates, ui

#663 Pre-release Ossiarch Bonereapers (fixes #308)
  src/army/ossiarch_bonereapers/endless_spells.ts
  src/army/ossiarch_bonereapers/index.ts
  src/army/ossiarch_bonereapers/scenery.ts
  src/army/ossiarch_bonereapers/units.ts
Labels: new army

#664 Quick fixes for a failed import
  package.json
  src/army/legions_of_nagash/units.ts
  src/components/input/importPdf/drop_container.tsx
  src/components/input/importPdf/parseFile.ts
  src/tests/battlescribe/battlescribeHTML.test.ts
  src/tests/fixtures/battlescribe/html/GHoN2.html
  src/utils/import/options.ts
  yarn.lock
Labels: battlescribe, rule updates

#665 Import fixes
  src/tests/battlescribe/battlescribeHTML.test.ts
  src/tests/fixtures/battlescribe/html/Sylvaneth2.html
  src/tests/fixtures/warscroll/json/1572497009675-Warscroll_Builder.json
  src/tests/warscroll/warscrollJson.test.ts
  src/utils/battlescribe/getters.ts
  src/utils/import/options.ts
Labels: battlescribe, warscroll-builder

#666 Add Ogor Mawtribes
  package.json
  src/army/ogor_mawtribes/abilities.ts
  src/army/ogor_mawtribes/allegiances.ts
  src/army/ogor_mawtribes/artifacts.ts
  src/army/ogor_mawtribes/endless_spells.ts
  src/army/ogor_mawtribes/index.ts
  src/army/ogor_mawtribes/scenery.ts
  src/army/ogor_mawtribes/spells.ts
  src/army/ogor_mawtribes/traits.ts
  src/army/ogor_mawtribes/units.ts
  src/army/sample_army/scenery.ts
  src/components/info/banners/app_banner.tsx
  src/meta/alliances.ts
  src/meta/army_list.ts
  src/meta/factions.ts
  src/utils/import/options.ts
  yarn.lock
Labels: new army
