Repository daviseford/aos-reminders, pull requests merged in 2019-09, with the labels that each got.

#329 Add Auth0, Stripe, Load&Save, and Subscription options (fixes #302, fixes #301, fixes #296, fixes #252)
  find
  package.json
  public/index.html
  src/api/preferenceApi.ts
  src/api/subscriptionApi.ts
  src/army/beasts_of_chaos/units.ts
  src/army/fyreslayers/units.ts
  src/army/sylvaneth/units.ts
  src/auth_config.json
  src/components/App.tsx
  src/components/info/card.tsx
  src/components/info/reminders.tsx
  src/components/input/army_builder.tsx
  src/components/input/army_builder_cards.ts
  src/components/input/cancellation_modal.tsx
  src/components/input/modalStyle.ts
  src/components/input/savedArmies/index.tsx
  src/components/input/savedArmies/load_army_btn.tsx
  src/components/input/savedArmies/paginate_buttons.tsx
  src/components/input/savedArmies/save_army_btn.tsx
  src/components/input/savedArmies/save_army_modal.tsx
  src/components/input/savedArmies/saved_armies.tsx
  src/components/input/savedArmies/saved_army_card.tsx
  src/components/input/savedArmies/saved_army_table.tsx
  src/components/input/savedArmies/show_saved_armies_btn.tsx
  src/components/input/toolbar.tsx
  src/components/page/header.tsx
  src/components/page/loading.tsx
  src/components/page/navbar.tsx
  src/components/page/privateRoute.tsx
  src/components/payment/plans.ts
  src/components/payment/pricingPlans.tsx
  src/components/routes/Home.tsx
  src/components/routes/Profile.tsx
  src/components/routes/Suscribe.tsx
  src/context/useSubscription.tsx
  src/css/index.scss
  src/ducks/duckUtils.ts
  src/ducks/index.ts
  src/ducks/selections.ts
  src/index.tsx
  src/react-auth0-wrapper.js
  src/tests/processReminders.test.ts
  src/types/savedArmy.ts
  src/types/store.ts
  src/types/subscription.ts
  src/types/user.ts
  src/utils/armyUtils.ts
  src/utils/env.ts
  src/utils/paginate.ts
  src/utils/processReminders.ts
  src/utils/subscriptionUtils.ts
  yarn.lock
Labels: enhancement, ui, v2.1

#334 Add an example image to Subscribe page
  public/img/load_army_example.png
  public/img/logo_border.png
  public/img/print-reminders.png
  src/components/App.tsx
  src/components/routes/Subscribe.tsx
Labels: ui

#336 Update plans.ts
  src/components/payment/plans.ts
Labels: subscriber feature

#338 Fix logout button in prod
  src/components/App.tsx
  src/components/page/navbar.tsx
  src/components/payment/pricingPlans.tsx
  src/components/routes/Subscribe.tsx
  src/utils/env.ts
Labels: subscriber feature

#344 Adding Gotrek (Fixes #335)
  src/army/grand_alliances/chaos/index.ts
  src/army/grand_alliances/chaos/units.ts
  src/army/grand_alliances/death/index.ts
  src/army/grand_alliances/death/units.ts
  src/army/grand_alliances/destruction/index.ts
  src/army/grand_alliances/destruction/units.ts
  src/army/grand_alliances/index.ts
  src/army/grand_alliances/order/index.ts
  src/army/grand_alliances/order/units.ts
  src/utils/getArmy.ts
Labels: rule updates

#345 Ossiarch bonelords
  src/army/Ossiarch_Bonereapers/abilities.ts
  src/army/Ossiarch_Bonereapers/allegiances.ts
  src/army/Ossiarch_Bonereapers/artifacts.ts
  src/army/Ossiarch_Bonereapers/endless_spells.ts
  src/army/Ossiarch_Bonereapers/index.ts
  src/army/Ossiarch_Bonereapers/scenery.ts
  src/army/Ossiarch_Bonereapers/spells.ts
  src/army/Ossiarch_Bonereapers/traits.ts
  src/army/Ossiarch_Bonereapers/units.ts
  src/meta/army_list.ts
  src/meta/factions.ts
Labels: new army

#348 Import from Warscroll Builder (fixes #319)
  package.json
  src/army/nighthaunt/units.ts
  src/army/slaanesh/units.ts
  src/army/stormcast_eternals/units.ts
  src/components/input/savedArmies/load_army_btn.tsx
  src/components/input/savedArmies/save_army_btn.tsx
  src/components/input/toolbar.tsx
  src/components/input/warscrollBuilder/dropContainer.tsx
  src/components/input/warscrollBuilder/dropZone.tsx
  src/css/index.scss
  src/utils/pdf/pdfUtils.ts
  src/utils/pdf/warscroll.ts
  src/utils/titleCase.ts
  yarn.lock
Labels: subscriber feature, ui

#350 Update UI for Import
  src/components/input/savedArmies/load_army_btn.tsx
  src/components/input/savedArmies/save_army_btn.tsx
  src/components/input/savedArmies/save_army_modal.tsx
  src/components/input/toolbar.tsx
  src/components/input/warscrollBuilder/dropZone.tsx
  src/components/input/warscrollBuilder/drop_container.tsx
  src/utils/analytics.ts
Labels: ui

#351 Add factionName to Import GA event
  src/components/input/warscrollBuilder/drop_zone.tsx
Labels: maintenance

#357 Fixed progeny of damnation
  src/army/slaanesh/spells.ts
Labels: rule updates

#355 Fix typo in Celestial Blades description
  src/army/stormcast_eternals/spells.ts
Labels: rule updates

#360 Post-Warscroll Launch: Rule Updates
  README.md
  src/army/skaven/units.ts
  src/army/slaanesh/spells.ts
  src/army/stormcast_eternals/spells.ts
  src/utils/pdf/warscroll.ts
Labels: rule updates

#361 Import Warscroll Builder Text Files (fixes #354 )
  src/components/input/warscrollBuilder/drop_container.tsx
  src/components/input/warscrollBuilder/drop_zone.tsx
  src/utils/warscroll/getWarscrollArmy.ts
  src/utils/warscroll/options.ts
Labels: enhancement

#363 More post-launch fixes
  README.md
  src/army/khorne/abilities.ts
  src/army/khorne/endless_spells.ts
  src/army/stormcast_eternals/units.ts
  src/utils/warscroll/getWarscrollArmy.ts
Labels: bug, enhancement, maintenance, rule updates

#364 Reduce package size by 102.8 KB
  package.json
  src/components/info/reminder.tsx
  src/components/info/reminders.tsx
  src/components/input/ally_army_builder.tsx
  src/components/input/savedArmies/saved_army_card.tsx
  src/components/input/savedArmies/saved_army_table.tsx
  src/components/input/select.tsx
  src/components/page/header.tsx
  src/components/print/print.tsx
  src/utils/processReminders.ts
  src/utils/textUtils.ts
  src/utils/warscroll/getWarscrollArmy.ts
  yarn.lock
Labels: maintenance

#366 Add Skyborne Slayers
  src/army/stormcast_eternals/units.ts
  src/utils/warscroll/getWarscrollArmy.ts
Labels: rule updates

#373 Fix Legions of Blood getting rejected
  src/utils/warscroll/options.ts
Labels: bug

#374 Better selections (fixes #326)
  src/army/sylvaneth/allegiances.ts
  src/tests/getArmy.test.ts
  src/types/army.ts
  src/utils/getArmy.ts
  src/utils/warscroll/getWarscrollArmy.ts
  src/utils/warscroll/options.ts
Labels: enhancement

#377 Separate out Legion of Blood
  src/army/legion_of_blood/abilities.ts
  src/army/legion_of_blood/artifacts.ts
  src/army/legion_of_blood/endless_spells.ts
  src/army/legion_of_blood/index.ts
  src/army/legion_of_blood/scenery.ts
  src/army/legion_of_blood/spells.ts
  src/army/legion_of_blood/traits.ts
  src/army/legion_of_blood/units.ts
  src/army/legions_of_nagash/spells.ts
  src/meta/army_list.ts
  src/meta/factions.ts
  src/utils/warscroll/options.ts
Labels: new army, rule updates

#380 Fix the timing of Spirit Flasks on Lord-Arcanums
  src/army/stormcast_eternals/units.ts
Labels: rule updates

#379 Fix typo in Liberator Prime rule name
  src/army/stormcast_eternals/units.ts
Labels: rule updates

#385 Log failed imports
  package.json
  src/army/fyreslayers/endless_spells.ts
  src/army/khorne/units.ts
  src/utils/analytics.ts
  src/utils/warscroll/getWarscrollArmy.ts
  src/utils/warscroll/options.ts
  yarn.lock
Labels: maintenance

#387 Adding failed imports (fixes #376 )
  src/army/legion_of_sacrament/abilities.ts
  src/army/legions_of_nagash/traits.ts
  src/utils/warscroll/getWarscrollArmy.ts
  src/utils/warscroll/options.ts
Labels: bug

#403 Warscroll Importer Updates (fixes #402)
  src/army/khorne/index.ts
  src/army/khorne/units.ts
  src/army/lethisian_army/index.ts
  src/army/lethisian_army/units.ts
  src/army/mercenary_companies/units.ts
  src/army/nurgle/index.ts
  src/army/nurgle/units.ts
  src/army/sample_army/index.ts
  src/army/sample_army/units.ts
  src/army/slaanesh/index.ts
  src/army/slaanesh/units.ts
  src/army/tamurkhans_horde/units.ts
  src/army/tzeentch/index.ts
  src/army/tzeentch/units.ts
  src/components/input/ally_army_builder.tsx
  src/components/input/army_builder.tsx
  src/components/input/savedArmies/load_army_btn.tsx
  src/components/input/toolbar.tsx
  src/components/input/warscrollBuilder/drop_container.tsx
  src/components/input/warscrollBuilder/drop_zone.tsx
  src/components/page/header.tsx
  src/ducks/army.ts
  src/tests/getArmy.test.ts
  src/tests/processReminders.test.ts
  src/types/army.ts
  src/types/warscrollTypes.ts
  src/utils/analytics.ts
  src/utils/armyUtils.ts
  src/utils/getArmy.ts
  src/utils/getArmy/getAllianceItems.ts
  src/utils/getArmy/getAllyArmyUnits.ts
  src/utils/getArmy/getArmy.ts
  src/utils/getArmy/getCollection.ts
  src/utils/getArmy/grandAllianceConfig.ts
  src/utils/getArmy/modify.ts
  src/utils/warscroll/allyData.ts
  src/utils/warscroll/getWarscrollArmy.ts
  src/utils/warscroll/warscrollUtils.ts
Labels: warscroll-builder

#404 Add error for short summary import (fixes #372)
  src/components/input/warscrollBuilder/drop_container.tsx
  src/components/input/warscrollBuilder/drop_zone.tsx
  src/types/warscrollTypes.ts
  src/utils/warscroll/getWarscrollArmy.ts
Labels: warscroll-builder

#405 Add Warscroll Import tests
  package.json
  src/army/slaanesh/traits.ts
  src/components/App.tsx
  src/components/input/warscrollBuilder/drop_container.tsx
  src/components/payment/pricingPlans.tsx
  src/tests/fixtures/warscroll/pdf/SeraphonMultipleAllies.pdf
  src/tests/fixtures/warscroll/pdf/SeraphonNoMetadata.pdf
  src/tests/fixtures/warscroll/pdf/SeraphonWithMetadata.pdf
  src/tests/fixtures/warscroll/pdf/SlaaneshList.pdf
  src/tests/fixtures/warscroll/txt/SeraphonMultipleAllies.txt
  src/tests/fixtures/warscroll/txt/SeraphonNoMetadata.txt
  src/tests/fixtures/warscroll/txt/SeraphonWithMetadata.txt
  src/tests/fixtures/warscroll/txt/ShortSummary.txt
  src/tests/warscrollImport.test.ts
  src/utils/analytics.ts
  src/utils/env.ts
  src/utils/warscroll/allyData.ts
  src/utils/warscroll/getWarscrollArmy.ts
  src/utils/warscroll/warscrollUtils.ts
  yarn.lock
Labels: warscroll-builder

#409 More failed imports
  src/army/nighthaunt/units.ts
  src/army/slaanesh/units.ts
  src/utils/warscroll/options.ts
Labels: warscroll-builder

#411 Add Github Actions for linting/testing PR's
  .github/workflows/nodejs.yml
  package.json
  src/tests/processReminders.test.ts
  src/types/store.ts
Labels: maintenance

#410 More tests
  src/army/skaven/units.ts
  src/tests/fixtures/warscroll/pdf/KOList.pdf
  src/tests/fixtures/warscroll/pdf/OrderMeetingEngagement.pdf
  src/tests/fixtures/warscroll/txt/OrderMeetingEngagement.txt
  src/tests/processReminders.test.ts
  src/tests/warscrollImport.test.ts
Labels: rule updates, warscroll-builder

#415 Great Bray Shaman fix
  src/army/grand_alliances/destruction/units.ts
  src/army/nurgle/units.ts
  src/army/slaanesh/units.ts
  src/army/tzeentch/units.ts
  src/utils/warscroll/options.ts
Labels: warscroll-builder

#417 Adjust warning text
  src/army/sylvaneth/allegiances.ts
  src/components/input/warscrollBuilder/drop_container.tsx
  src/utils/analytics.ts
  src/utils/warscroll/getWarscrollArmy.ts
Labels: ui, warscroll-builder

#418 Update Warrior Indominate
  src/army/fyreslayers/allegiances.ts
Labels: rule updates

#419 Update ally warning
  src/components/input/warscrollBuilder/drop_container.tsx
  src/types/warscrollTypes.ts
  src/utils/warscroll/allyData.ts
  src/utils/warscroll/getWarscrollArmy.ts
  src/utils/warscroll/warscrollUtils.ts
Labels: ui, warscroll-builder

#420 Add Better Error - thx to AoS Shorts
  src/tests/fixtures/warscroll/pdf/Dreadwood.pdf
  src/utils/warscroll/getWarscrollArmy.ts
Labels: warscroll-builder

#422 Rewrite Azyr regexes
  src/components/input/azyr/azyrPdf.ts
  src/tests/azyrImport.test.ts
  src/tests/fixtures/azyr/pdf/Beasts.pdf
  src/tests/fixtures/azyr/pdf/GHoN.pdf
  src/tests/fixtures/azyr/pdf/KO.plus.pdf
  src/tests/fixtures/azyr/pdf/Khorne (1).pdf
  src/tests/fixtures/azyr/pdf/Nurgle.pdf
  src/tests/fixtures/azyr/pdf/Nurgle_2.pdf
  src/tests/fixtures/azyr/pdf/Skaven.pdf
  src/tests/fixtures/azyr/pdf/Tzeentch.pdf
  src/utils/azyr/Cats.and.Judicators.2000.pdf
Labels: azyr

#424 Set SelectMulti inputs to stay open after selections
  src/components/input/select.tsx
Labels: ui

#429 Fix typo in Thunderscorn Stormherd (fixes #427)
  src/army/beasts_of_chaos/units.ts
Labels: rule updates

#432 Post-Azyr release
  README.md
  src/utils/azyr/azyrPdf.ts
Labels: azyr

#433 More Azyr updates
  package.json
  public/img/azyr-example1.gif
  src/army/flesh_eater_courts/endless_spells.ts
  src/army/generic/endless_spells.ts
  src/army/idoneth/units.ts
  src/army/nighthaunt/endless_spells.ts
  src/army/tamurkhans_horde/index.ts
  src/army/tzeentch/units.ts
  src/components/payment/pricingPlans.tsx
  src/components/routes/Subscribe.tsx
  src/utils/import/options.ts
  yarn.lock
Labels: azyr, ui

#437 Fixes #435
  src/army/stormcast_eternals/units.ts
Labels: rule updates

#438 UI/Validator Updates
  README.md
  package.json
  src/army/slaves_to_darkness/units.ts
  src/components/input/importPdf/drop_container.tsx
  src/components/page/footer.tsx
  src/components/page/navbar.tsx
  src/components/payment/pricingPlans.tsx
  src/components/routes/Subscribe.tsx
  src/tests/fixtures/azyr/json/BCR1.json
  src/utils/azyr/azyrPdf.ts
  src/utils/import/allyData.ts
  src/utils/import/checkErrors.ts
  src/utils/import/checkImportSelection.ts
  src/utils/import/index.ts
  src/utils/import/options.ts
  src/utils/import/selectionLookup.ts
  src/utils/import/validators.ts
  src/utils/import/warnings.ts
  src/utils/mapListToDict.ts
  src/utils/warscroll/getWarscrollArmy.ts
  yarn.lock
Labels: azyr, maintenance, ui

#445 Fix SCE Mount trait
  src/army/soulblight/units.ts
  src/army/stormcast_eternals/traits.ts
  src/tests/fixtures/azyr/json/Stormcast4.json
  src/tests/fixtures/azyr/pdf/Stormcast4.pdf
  src/tests/getAzyrArmy.test.ts
  src/utils/import/options.ts
Labels: warscroll-builder

#446 Reverse SCE commit
  src/army/stormcast_eternals/traits.ts
  src/tests/getAzyrArmy.test.ts
  src/utils/import/options.ts
  src/utils/textUtils.ts
Labels: rule updates

#449 Unit fixes
  package.json
  src/army/beasts_of_chaos/endless_spells.ts
  src/army/slaanesh/endless_spells.ts
  src/army/soulblight/units.ts
  src/army/sylvaneth/units.ts
  src/utils/filterUtils.ts
  src/utils/import/options.ts
  yarn.lock
Labels: maintenance, rule updates

#451 Fixes #450
  src/utils/import/options.ts
Labels: rule updates

#461 Fix for KO Trait import
  src/tests/azyrImport.test.ts
  src/tests/fixtures/azyr/json/KO4.json
  src/tests/fixtures/azyr/json/KO5.json
  src/tests/fixtures/azyr/pdf/KO4.pdf
  src/tests/fixtures/azyr/pdf/KO5.pdf
  src/tests/getAzyrArmy.test.ts
  src/utils/azyr/getAzyrArmy.ts
Labels: azyr, bug

#463 Update Aethervoid Pendulum rules (fixes #462)
  src/army/generic/endless_spells.ts
  src/components/page/contact.tsx
Labels: rule updates

#464 Add a way to close import errors
  src/components/input/importPdf/drop_container.tsx
Labels: ui

#467 Add scenery
  src/army/generic/scenery.ts
Labels: rule updates

#468 Add warscrolls
  src/army/legions_of_nagash/units.ts
  src/army/nighthaunt/units.ts
Labels: rule updates

#448 PDF Download
  README.md
  clean.js
  package.json
  src/army/beastclaw_raiders/units.ts
  src/army/daughters_of_khaine/units.ts
  src/army/gloomspite/scenery.ts
  src/army/idoneth/abilities.ts
  src/army/idoneth/allegiances.ts
  src/army/idoneth/artifacts.ts
  src/army/idoneth/traits.ts
  src/army/idoneth/units.ts
  src/army/ironjawz/spells.ts
  src/army/ironjawz/units.ts
  src/army/nighthaunt/endless_spells.ts
  src/army/nurgle/units.ts
  src/army/seraphon/units.ts
  src/army/slaanesh/endless_spells.ts
  src/army/slaanesh/units.ts
  src/army/stormcast_eternals/endless_spells.ts
  src/army/stormcast_eternals/units.ts
  src/army/sylvaneth/units.ts
  src/army/tzeentch/abilities.ts
  src/army/tzeentch/units.ts
  src/army/wanderers/units.ts
  src/components/App.tsx
  src/components/info/reminder.tsx
  src/components/info/reminders.tsx
  src/components/input/importPdf/drop_container.tsx
  src/components/input/importPdf/parseFile.ts
  src/components/input/savedArmies/saved_armies.tsx
  src/components/input/toolbar.tsx
  src/components/page/loading.tsx
  src/components/page/navbar.tsx
  src/components/print/pdfButton.tsx
  src/components/print/pdfModal.tsx
  src/components/routes/Home.tsx
  src/components/routes/Profile.tsx
  src/components/routes/Subscribe.tsx
  src/context/useSubscription.tsx
  src/css/index.scss
  src/theme/helperClasses.ts
  src/utils/analytics.ts
  src/utils/azyr/azyrPdf.ts
  src/utils/pdf/generate/generatePdf.ts
  src/utils/pdf/generate/logo.ts
  src/utils/pdf/generate/styles.ts
  src/utils/textUtils.ts
  yarn.lock
Labels: enhancement, in progress, subscriber feature, ui

#473 Ecommerce updates
  package.json
  public/index.html
  src/components/App.tsx
  src/components/payment/asyncStripeProvider.tsx
  src/components/payment/pricingPlans.tsx
  src/index.tsx
  src/utils/analytics.ts
  yarn.lock
Labels: maintenance

#474 Code splitting (fixes #472)
  src/components/App.tsx
  src/components/info/reminders.tsx
  src/components/input/ally_armies.tsx
  src/components/page/footer.tsx
  src/components/page/loading.tsx
  src/components/print/printArmy.tsx
  src/components/print/printFooter.tsx
  src/components/routes/Home.tsx
  src/css/animations.css
  src/utils/handleCheckout.ts
Labels: maintenance

#475 Loading tweaks
  src/components/routes/Profile.tsx
  src/css/animations.css
Labels: ui

#477 Update redux-starter-kit (fixes #343)
  package.json
  src/components/info/card.tsx
  src/components/info/reminder.tsx
  src/components/info/reminders.tsx
  src/components/input/ally_armies.tsx
  src/components/input/ally_army_builder.tsx
  src/components/input/army_builder.tsx
  src/components/input/savedArmies/save_army_btn.tsx
  src/components/input/toolbar.tsx
  src/components/page/header.tsx
  src/components/print/pdfButton.tsx
  src/components/print/printArmy.tsx
  src/ducks/army.ts
  src/ducks/duckUtils.ts
  src/ducks/factionNames.ts
  src/ducks/index.ts
  src/ducks/realmscape.ts
  src/ducks/selections.ts
  src/ducks/selectors.ts
  src/ducks/visibility.ts
  src/types/store.ts
  yarn.lock
Labels: maintenance

#478 Add Spinners
  src/components/App.tsx
  src/components/helpers/spinner.tsx
  src/components/helpers/suspenseFallbacks.tsx
  src/components/input/army_builder.tsx
  src/components/input/importPdf/drop_zone.tsx
  src/components/input/importPdf/parseFile.ts
  src/components/input/savedArmies/index.tsx
  src/components/input/savedArmies/saved_armies.tsx
  src/components/input/savedArmies/show_saved_armies_btn.tsx
  src/components/input/toolbar.tsx
  src/components/page/homeHeader.tsx
  src/components/page/navbar.tsx
  src/components/routes/Home.tsx
  src/components/routes/Profile.tsx
  src/components/routes/Subscribe.tsx
  src/theme/helperClasses.ts
Labels: ui

#480 Updating KO (Fixes #479)
  src/army/kharadron_overlords/abilities.ts
  src/army/kharadron_overlords/artifacts.ts
  src/army/kharadron_overlords/index.ts
  src/army/kharadron_overlords/traits.ts
Labels: rule updates

#483 Fix import errors that occurred when importing a bad Warscroll file
  src/components/input/importPdf/drop_container.tsx
  src/components/input/importPdf/drop_zone.tsx
  src/components/input/importPdf/parseFile.ts
  src/components/print/pdfModal.tsx
  src/types/import.ts
  src/utils/azyr/azyrPdf.ts
  src/utils/import/options.ts
Labels: warscroll-builder

#485 Fix header bug and add modal spinners
  src/components/input/savedArmies/delete_army_modal.tsx
  src/components/input/savedArmies/save_army_modal.tsx
  src/components/input/savedArmies/saved_army_card.tsx
  src/components/input/savedArmies/update_name_modal.tsx
  src/context/useSavedArmies.tsx
Labels: bug, subscriber feature, ui

#488 Keep it sync
  package.json
  src/components/helpers/spinner.tsx
  src/components/helpers/suspenseFallbacks.tsx
  src/components/input/ally_armies.tsx
  src/components/input/ally_army_builder.tsx
  src/components/input/importPdf/drop_container.tsx
  src/components/input/importPdf/parseFile.ts
  src/components/input/savedArmies/load_army_btn.tsx
  src/components/input/savedArmies/save_army_btn.tsx
  src/components/input/select.tsx
  src/components/input/toolbar/add_ally_btn.tsx
  src/components/input/toolbar/import_army_btn.tsx
  src/components/input/toolbar/toolbar.tsx
  src/components/page/homeHeader.tsx
  src/components/routes/Home.tsx
  src/context/useSavedArmies.tsx
  src/context/useSubscription.tsx
  src/css/index.scss
  src/css/theme.scss
  src/ducks/army.ts
  src/theme/helperClasses.ts
  src/utils/processReminders.ts
  yarn.lock
Labels: bug, maintenance, ui

#489 Update Ironjawz Unit cards
  src/army/ironjawz/units.ts
Labels: new army

#490 UI Refinements
  public/img/aos-reminders.png
  public/img/load_army_example.png
  public/img/logo.png
  public/img/logo_border.png
  public/img/logo_noURL.png
  public/img/print-reminders.png
  src/components/input/savedArmies/delete_army_modal.tsx
  src/components/input/savedArmies/paginate_buttons.tsx
  src/components/input/savedArmies/save_army_btn.tsx
  src/components/input/savedArmies/save_army_modal.tsx
  src/components/input/savedArmies/saved_army_card.tsx
  src/components/input/savedArmies/update_name_btn.tsx
  src/components/input/savedArmies/update_name_modal.tsx
  src/components/print/pdfButton.tsx
  src/components/print/pdfModal.tsx
  src/components/routes/Profile.tsx
  src/meta/army_list.ts
  src/theme/helperClasses.ts
  src/utils/getArmy/getAllianceItems.ts
  src/utils/getArmy/getAllyArmyUnits.ts
  src/utils/getArmy/getArmy.ts
Labels: ui

#491 Reduce subscribe gif size
  package.json
  public/img/azyr-example1.mp4
  src/components/routes/Subscribe.tsx
Labels: ui

#492 UI Updates
  src/components/input/savedArmies/load_army_btn.tsx
  src/components/input/savedArmies/saved_armies.tsx
  src/components/input/savedArmies/saved_army_card.tsx
  src/context/useSavedArmies.tsx
  src/css/animations.css
Labels: ui

#495 Added Bonesplitterz Unit Updates
  src/army/bonesplitterz/units.ts
  src/army/ironjawz/units.ts
Labels: rule updates
