Repository daviseford/aos-reminders, pull requests merged in 2019-12, with the labels that each got.

#778 Add script to automatically suggest rule phases (fixes #772)
  .gitignore
  README.md
  package.json
  src/army/cities_of_sigmar/units.ts
  src/army/dispossessed/units.ts
  src/army/fyreslayers/units.ts
  src/army/gloomspite/units.ts
  src/army/grand_alliances/chaos/units.ts
  src/army/idoneth/units.ts
  src/army/kharadron_overlords/units.ts
  src/army/legions_of_azgorh/units.ts
  src/army/nighthaunt/units.ts
  src/army/nurgle/units.ts
  src/army/ogor_mawtribes/units.ts
  src/army/skaven/units.ts
  src/army/slaves_to_darkness/units.ts
  src/utils/dev/exportToSheet.ts
  src/utils/dev/verify.ts
  tsconfig.json
  yarn.lock
Labels: maintenance, rule updates

#780 Export army to S3 on save
  package.json
  src/api/preferenceApi.ts
  src/components/input/importPdf/drop_container.tsx
  src/components/input/shareArmy/share_army_modal.tsx
  src/components/print/pdfButton.tsx
  src/context/useSavedArmies.tsx
  src/utils/armyUtils.ts
  yarn.lock
Labels: enhancement, maintenance

#785 Remove Summoning errors from Battlescribe
  package.json
  src/ducks/army.ts
  src/ducks/factionNames.ts
  src/ducks/realmscape.ts
  src/ducks/selections.ts
  src/ducks/visibility.ts
  src/tests/battlescribe/battlescribeHTML.test.ts
  src/tests/fixtures/battlescribe/html/Khorne5.html
  src/utils/battlescribe/getters.ts
  yarn.lock
Labels: battlescribe, maintenance

#786 Warclans rules update (fixes #759)
  src/army/bonesplitterz/units.ts
  src/army/ironjawz/units.ts
Labels: rule updates

#788 Update Anointed rule, change Update button position
  src/army/cities_of_sigmar/units.ts
  src/components/input/savedArmies/loaded_army_header.tsx
  src/components/input/savedArmies/update_army_btn.tsx
  src/components/input/toolbar/toolbar.tsx
  src/context/useSavedArmies.tsx
Labels: rule updates, ui

#790 Show selection counts on collapsed cards
  src/components/info/card.tsx
  src/css/index.scss
  src/tests/battlescribe/battlescribeHTML.test.ts
Labels: ui

#792 Fix some import bugs, missing units, and KO rule
  package.json
  src/army/kharadron_overlords/units.ts
  src/army/nighthaunt/units.ts
  src/army/slaves_to_darkness/units.ts
  src/tests/azyr/getAzyrArmy.test.ts
  src/tests/battlescribe/battlescribeHTML.test.ts
  src/tests/fixtures/azyr/json/OgorMawtribes4.json
  src/tests/fixtures/battlescribe/html/Mawtribes2.html
  src/tests/fixtures/battlescribe/html/Nighthaunt5.html
  src/tests/fixtures/battlescribe/html/Sylvaneth3.html
  src/tests/fixtures/warscroll/json/1576047037925-Warscroll_Builder.json
  src/tests/fixtures/warscroll/json/1576093463575-Warscroll_Builder.json
  src/tests/warscroll/warscrollJson.test.ts
  src/utils/battlescribe/getters.ts
  src/utils/battlescribe/parseHTML.ts
  yarn.lock
Labels: azyr, battlescribe, rule updates, warscroll-builder

#797 Compact PDF option
  package.json
  src/components/input/savedArmies/save_army_btn.tsx
  src/components/input/shareArmy/share_army_btn.tsx
  src/components/print/pdfButton.tsx
  src/components/print/pdfModal.tsx
  src/tests/battlescribe/battlescribeHTML.test.ts
  src/types/pdf.ts
  src/utils/analytics.ts
  src/utils/pdf/generate/generatePdf.ts
  src/utils/pdf/generate/layouts/compact.ts
  src/utils/pdf/generate/layouts/compactLayoutUtils.ts
  src/utils/pdf/generate/layouts/default.ts
  src/utils/pdf/generate/layouts/layoutUtils.ts
  src/utils/pdf/generate/styles.ts
  yarn.lock
Labels: ui

#800 Remove Dispossessed, consolidate PDF code
  package.json
  src/army/dispossessed/abilities.ts
  src/army/dispossessed/artifacts.ts
  src/army/dispossessed/index.ts
  src/army/dispossessed/traits.ts
  src/army/dispossessed/units.ts
  src/components/print/pdfButton.tsx
  src/components/print/pdfModal.tsx
  src/meta/army_list.ts
  src/meta/factions.ts
  src/tests/azyr/azyrImport.test.ts
  src/tests/azyr/getAzyrArmy.test.ts
  src/tests/fixtures/azyr/json/Dispossessed1.json
  src/tests/fixtures/azyr/pdf/Dispossessed1.pdf
  src/tests/fixtures/battlescribe/html/Dispossessed1.html
  src/tests/processReminders.test.ts
  src/types/pdf.ts
  src/utils/import/options.ts
  src/utils/pdf/generate/generatePdf.ts
  src/utils/pdf/generate/layouts/compact.ts
  src/utils/pdf/generate/layouts/compactLayoutUtils.ts
  src/utils/pdf/generate/layouts/default.ts
  src/utils/pdf/generate/layouts/layoutUtils.ts
  yarn.lock
Labels: pdf, ui

#801 Fix Slaves to Darkness import errors post-battletome
  package.json
  src/army/slaves_to_darkness/units.ts
  src/army/sylvaneth/units.ts
  src/tests/azyr/azyrImport.test.ts
  src/tests/azyr/getAzyrArmy.test.ts
  src/tests/battlescribe/battlescribeHTML.test.ts
  src/tests/fixtures/azyr/json/KO7.json
  src/tests/fixtures/azyr/json/StD1.json
  src/tests/fixtures/azyr/json/StD2.json
  src/tests/fixtures/azyr/json/StD3.json
  src/tests/fixtures/azyr/json/StD4.json
  src/tests/fixtures/azyr/json/StD5.json
  src/tests/fixtures/azyr/json/StD6.json
  src/tests/fixtures/azyr/json/StD7.json
  src/tests/fixtures/battlescribe/html/Mawtribes3.html
  src/tests/fixtures/warscroll/json/1576230943609-Warscroll_Builder.json
  src/tests/fixtures/warscroll/json/1576328165962-Warscroll_Builder.json
  src/tests/fixtures/warscroll/json/1576328837058-Warscroll_Builder.json
  src/tests/fixtures/warscroll/json/1576364961328-Warscroll_Builder.json
  src/tests/fixtures/warscroll/json/1576418593609-Warscroll_Builder.json
  src/tests/fixtures/warscroll/json/1576448761220-Warscroll_Builder.json
  src/tests/fixtures/warscroll/json/1576493074441-Warscroll_Builder.json
  src/tests/fixtures/warscroll/json/1576502239768-Warscroll_Builder.json
  src/tests/warscroll/warscrollJson.test.ts
  src/tests/warscroll/warscrollPdf.test.ts
  src/utils/azyr/azyrPdf.ts
  src/utils/import/allyData.ts
  src/utils/import/options.ts
  src/utils/warscroll/warscrollUtils.ts
  yarn.lock
Labels: azyr, battlescribe, warscroll-builder

#802 Add Nurgle FAQ update
  src/army/nurgle/units.ts
Labels: rule updates

#803 Orruk FAQ
  src/army/ironjawz/units.ts
Labels: rule updates

#804 Ossiarch Bonereapers FAQ
  src/army/ossiarch_bonereapers/units.ts
Labels: rule updates

#806 Rest of the December 2019 FAQs
  src/army/bonesplitterz/units.ts
  src/army/cities_of_sigmar/allegiances.ts
  src/army/cities_of_sigmar/units.ts
  src/army/daughters_of_khaine/units.ts
  src/army/fyreslayers/allegiances.ts
  src/army/fyreslayers/scenery.ts
  src/army/fyreslayers/traits.ts
  src/army/fyreslayers/units.ts
  src/army/generic/effects.ts
  src/army/generic/realmscape_features.ts
  src/army/generic/realmscape_spells.ts
  src/army/gloomspite/shared.ts
  src/army/gloomspite/traits.ts
  src/army/gloomspite/units.ts
  src/army/grand_alliances/chaos/units.ts
  src/army/greenskinz/units.ts
  src/army/idoneth/abilities.ts
  src/army/ironjawz/units.ts
  src/army/kharadron_overlords/allegiances.ts
  src/army/kharadron_overlords/artifacts.ts
  src/army/kharadron_overlords/units.ts
  src/army/khorne/allegiances.ts
  src/army/nighthaunt/spells.ts
  src/army/ogor_mawtribes/artifacts.ts
  src/army/ossiarch_bonereapers/spells.ts
  src/army/slaanesh/abilities.ts
  src/army/slaves_to_darkness/abilities.ts
  src/army/slaves_to_darkness/allegiances.ts
  src/army/slaves_to_darkness/artifacts.ts
  src/army/slaves_to_darkness/endless_spells.ts
  src/army/slaves_to_darkness/traits.ts
  src/army/slaves_to_darkness/units.ts
  src/army/tamurkhans_horde/units.ts
Labels: rule updates

#807 Add new Plague monk warscroll
  package.json
  src/army/skaven/units.ts
  yarn.lock
Labels: rule updates

#808 Warscroll Builder STD fixes
  package.json
  src/army/khorne/artifacts.ts
  src/army/nighthaunt/units.ts
  src/army/slaves_to_darkness/artifacts.ts
  src/components/input/importPdf/parseFile.ts
  src/tests/azyr/getAzyrArmy.test.ts
  src/tests/fixtures/azyr/json/BCR3.json
  src/tests/fixtures/warscroll/json/1576513040341-Warscroll_Builder.json
  src/tests/fixtures/warscroll/json/1576527400569-Warscroll_Builder.json
  src/tests/fixtures/warscroll/json/1576533398655-Warscroll_Builder.json
  src/tests/fixtures/warscroll/json/1576681454336-Warscroll_Builder.json
  src/tests/warscroll/warscrollJson.test.ts
  src/utils/import/options.ts
  src/utils/warscroll/getWarscrollArmy.ts
  yarn.lock
Labels: azyr, rule updates, warscroll-builder

#812 Imports
  package.json
  src/army/cities_of_sigmar/units.ts
  src/army/flesh_eater_courts/artifacts.ts
  src/tests/battlescribe/battlescribeHTML.test.ts
  src/tests/fixtures/battlescribe/html/Fyreslayers8.html
  src/tests/fixtures/battlescribe/html/StD2.html
  src/tests/fixtures/battlescribe/html/Stormcast6.html
  src/tests/fixtures/warscroll/json/1576858425499-Warscroll_Builder.json
  src/tests/warscroll/warscrollJson.test.ts
  src/utils/battlescribe/battlescribeUtils.ts
  yarn.lock
Labels: azyr, battlescribe, rule updates, warscroll-builder

#813 Add legacy lizardmen scrolls
  src/army/seraphon/units.ts
Labels: rule updates

#818 Add big names
  package.json
  src/army/ogor_mawtribes/traits.ts
  src/army/ogor_mawtribes/units.ts
  yarn.lock
Labels: rule updates

#819 End Half Off Sale, fixes Master of Star Rituals
  src/army/ironjawz/traits.ts
  src/army/seraphon/traits.ts
  src/army/seraphon/units.ts
  src/utils/plans.ts
Labels: rule updates, ui

#809 Game mode
  package.json
  src/components/info/confirm_dismiss_notification_modal.tsx
  src/components/info/reminder.tsx
  src/components/info/reminders.tsx
  src/components/info/visibilityToggle.tsx
  src/components/input/savedArmies/reset_changes_btn.tsx
  src/components/input/savedArmies/update_army_btn.tsx
  src/components/input/toggle_game_mode.tsx
  src/components/input/toolbar/toolbar.tsx
  src/components/page/homeHeader.tsx
  src/components/routes/Home.tsx
  src/context/useAppStatus.tsx
  src/context/useSavedArmies.tsx
  src/tests/utils.test.ts
  src/utils/localStore.ts
  src/utils/mapSizesToProps.ts
  src/utils/pdf/generate/getVisibleReminders.ts
  src/utils/pdf/generate/layouts/compact.ts
  src/utils/pdf/generate/layouts/default.ts
  src/utils/reminderUtils.ts
  yarn.lock
Labels: enhancement, ui

#820 Add import tests and display version number in footer
  src/army/grand_alliances/order/units.ts
  src/components/page/footer.tsx
  src/tests/azyr/getAzyrArmy.test.ts
  src/tests/battlescribe/battlescribeHTML.test.ts
  src/tests/fixtures/azyr/json/BigWaaagh3.json
  src/tests/fixtures/azyr/json/KO8.json
  src/tests/fixtures/azyr/json/Seraphon3.json
  src/tests/fixtures/azyr/json/Seraphon4.json
  src/tests/fixtures/azyr/json/Slaanesh3.json
  src/tests/fixtures/azyr/json/StD10.json
  src/tests/fixtures/azyr/json/StD8.json
  src/tests/fixtures/azyr/json/StD9.json
  src/tests/fixtures/battlescribe/html/BigWaaagh4.html
  src/tests/fixtures/battlescribe/html/LoG1.html
  src/tests/fixtures/battlescribe/html/Soulblight2.html
  src/tests/fixtures/battlescribe/html/StD3.html
  src/tests/fixtures/battlescribe/html/Stormcast3.html
  src/tests/fixtures/battlescribe/html/Tzeentch2.html
  src/tests/fixtures/warscroll/json/1577088536258-Warscroll_Builder.json
  src/tests/fixtures/warscroll/json/1577400809137-Warscroll_Builder.json
  src/tests/fixtures/warscroll/json/1577400907052-Warscroll_Builder.json
  src/tests/fixtures/warscroll/json/1577741192555-Warscroll_Builder.json
  src/tests/warscroll/warscrollJson.test.ts
  src/utils/azyr/azyrPdf.ts
  src/utils/import/options.ts
  src/utils/warscroll/getWarscrollArmy.ts
Labels: azyr, battlescribe, rule updates, ui, warscroll-builder
