Repository daviseford/aos-reminders, pull requests merged in 2019-08, with the labels that each got.

#157 * Add Slaves to Darkness (Fixes #156)
  src/army/slaves_to_darkness/abilities.ts
  src/army/slaves_to_darkness/artifacts.ts
  src/army/slaves_to_darkness/index.ts
  src/army/slaves_to_darkness/traits.ts
  src/army/slaves_to_darkness/units.ts
  src/meta/army_list.ts
  src/meta/factions.ts
Labels: new army

#141 Add support for spells and endless spells (fixes #95) (fixes #66)
  src/army/daughters_of_khaine/index.ts
  src/army/daughters_of_khaine/spells.ts
  src/army/fyreslayers/index.ts
  src/army/fyreslayers/spells.ts
  src/army/legions_of_azgorh/index.ts
  src/army/legions_of_azgorh/spells.ts
  src/army/malign_sorcery/artifacts.ts
  src/army/malign_sorcery/endless_spells.ts
  src/army/malign_sorcery/index.ts
  src/army/malign_sorcery/realmscape_features.ts
  src/army/malign_sorcery/spells.ts
  src/army/nurgle/index.ts
  src/army/nurgle/spells.ts
  src/army/sample_army/endless_spells.ts
  src/army/sample_army/index.ts
  src/army/sample_army/spells.ts
  src/army/slaanesh/endless_spells.ts
  src/army/slaanesh/index.ts
  src/army/slaanesh/spells.ts
  src/components/App.tsx
  src/components/info/reminders.tsx
  src/components/input/army_builder.tsx
  src/components/input/select.tsx
  src/components/input/select_realmscape.tsx
  src/components/page/header.tsx
  src/components/print/print.tsx
  src/ducks/army.ts
  src/ducks/realmscape.ts
  src/ducks/selections.ts
  src/meta/army_list.ts
  src/types/army.ts
  src/types/data.ts
  src/types/realmscapes.ts
  src/types/selections.ts
  src/utils/getArmy.ts
  src/utils/processGame.ts
  src/utils/processReminders.ts
Labels: enhancement

#165 Add Seraphon spells, Generic spells (fixes #163)
  src/army/generic/endless_spells.ts
  src/army/generic/index.ts
  src/army/generic/spells.ts
  src/army/malign_sorcery/index.ts
  src/army/malign_sorcery/spells.ts
  src/army/seraphon/index.ts
  src/army/seraphon/spells.ts
  src/utils/getArmy.ts
Labels: rule updates

#174 * Chaos/DoK updates (Fixes #160)
  src/army/daughters_of_khaine/endless_spells.ts
  src/army/daughters_of_khaine/index.ts
  src/army/daughters_of_khaine/spells.ts
  src/army/everchosen/endless_spells.ts
  src/army/everchosen/index.ts
  src/army/everchosen/spells.ts
  src/army/everchosen/units.ts
  src/army/khorne/abilities.ts
  src/army/khorne/endless_spells.ts
  src/army/khorne/index.ts
  src/army/khorne/spells.ts
  src/army/nurgle/endless_spells.ts
  src/army/nurgle/index.ts
  src/army/slaanesh/abilities.ts
  src/army/slaanesh/endless_spells.ts
  src/army/slaanesh/spells.ts
  src/army/slaanesh/units.ts
  src/army/slaves_to_darkness/endless_spells.ts
  src/army/slaves_to_darkness/index.ts
  src/army/slaves_to_darkness/spells.ts
  src/army/tamurkhans_horde/endless_spells.ts
  src/army/tamurkhans_horde/index.ts
  src/army/tamurkhans_horde/spells.ts
  src/army/tzeentch/endless_spells.ts
  src/army/tzeentch/index.ts
  src/army/tzeentch/spells.ts
Labels: rule updates

#177 More spell files added against #160.
  src/army/beastclaw_raiders/endless_spells.ts
  src/army/beastclaw_raiders/index.ts
  src/army/beastclaw_raiders/spells.ts
  src/army/dispossessed/endless_spells.ts
  src/army/dispossessed/index.ts
  src/army/dispossessed/spells.ts
  src/army/ironjawz/endless_spells.ts
  src/army/ironjawz/index.ts
  src/army/ironjawz/spells.ts
  src/army/kharadron_overlords/endless_spells.ts
  src/army/kharadron_overlords/index.ts
  src/army/kharadron_overlords/spells.ts
Labels: rule updates

#178 De verbosify sc
  src/army/stormcast_eternals/abilities.ts
  src/army/stormcast_eternals/artifacts.ts
  src/army/stormcast_eternals/endless_spells.ts
  src/army/stormcast_eternals/traits.ts
  src/army/stormcast_eternals/units.ts
Labels: rule updates

#175 Allow multiple allies (fixes #148)
  src/components/App.tsx
  src/components/info/reminders.tsx
  src/components/input/ally_armies.tsx
  src/components/input/ally_army_builder.tsx
  src/components/input/toolbar.tsx
  src/components/print/print.tsx
  src/ducks/army.ts
  src/ducks/factionNames.ts
  src/ducks/selections.ts
  src/types/army.ts
  src/utils/processReminders.ts
  src/utils/withSelect.ts
Labels: enhancement

#181 Small tweaks to print performance (don't render if not printing)
  package.json
  src/components/App.tsx
  src/components/print/print.tsx
  yarn.lock
Labels: enhancement

#182 Combine similar rules into one entry (fixes #173)
  src/utils/processReminders.ts
Labels: enhancement

#184 Fixing merged entries (fixes #183) (#182)
  README.md
  src/components/App.test.tsx
  src/tests/__mock.ts
  src/tests/utils.test.ts
  src/types/army.ts
  src/utils/processReminders.ts
Labels: bug, enhancement

#185 Add Print Warning for Firefox users (also fixes #131)
  package.json
  src/components/info/reminders.tsx
  src/components/input/toolbar.tsx
  yarn.lock
Labels: bug, enhancement

#187 Fix merging (fixes #186)
  src/army/generic/endless_spells.ts
  src/army/nighthaunt/endless_spells.ts
  src/army/slaanesh/endless_spells.ts
  src/tests/utils.test.ts
  src/utils/processReminders.ts
Labels: bug

#188 * Added Skaven endless/spells (#160)
  src/army/skaven/abilities.ts
  src/army/skaven/endless_spells.ts
  src/army/skaven/index.ts
  src/army/skaven/spells.ts
Labels: rule updates

#189 Update Slaanesh spells
  src/army/slaanesh/endless_spells.ts
Labels: rule updates

#190 Use immer, update clean.js, condense spell descriptions
  clean.js
  src/army/generic/endless_spells.ts
  src/army/nighthaunt/endless_spells.ts
  src/army/seraphon/spells.ts
  src/army/sylvaneth/endless_spells.ts
  src/meta/army_list.ts
  src/utils/getArmy.ts
Labels: enhancement, rule updates

#191 Added start of round phase for Everblaze Comet
  src/army/stormcast_eternals/endless_spells.ts
Labels: rule updates

#201 Add FEC spells (#160)
  src/army/flesh_eater_courts/spells.ts
Labels: rule updates

#202 Add Skaven traits and abilities (fixes #193)
  src/army/sample_army/allegiances.ts
  src/army/skaven/abilities.ts
  src/army/skaven/allegiances.ts
  src/army/skaven/traits.ts
Labels: rule updates

#203 Update analytics
  README.md
  clean.js
  src/components/App.tsx
  src/components/info/donate.tsx
  src/components/input/ally_army_builder.tsx
  src/components/page/footer.tsx
  src/components/page/header.tsx
  src/utils/analytics.ts
Labels: bug

#207 Add Gutbusters (fixes #204)
  src/army/gutbusters/abilities.ts
  src/army/gutbusters/allegiances.ts
  src/army/gutbusters/artifacts.ts
  src/army/gutbusters/endless_spells.ts
  src/army/gutbusters/index.ts
  src/army/gutbusters/spells.ts
  src/army/gutbusters/traits.ts
  src/army/gutbusters/units.ts
  src/meta/army_list.ts
  src/meta/factions.ts
Labels: new army

#212 Misc. fixes
  package.json
  src/army/grand_alliances/destruction/artifacts.ts
  src/components/App.tsx
  src/components/info/reminders.css
  src/components/print/print.tsx
  yarn.lock
Labels: bug, enhancement

#213 Slannesh updates
  src/army/slaanesh/abilities.ts
  src/army/slaanesh/allegiances.ts
  src/army/slaanesh/artifacts.ts
  src/army/slaanesh/traits.ts
Labels: rule updates

#214 Updates to property tagging
  src/army/beastclaw_raiders/abilities.ts
  src/army/daughters_of_khaine/abilities.ts
  src/army/dispossessed/abilities.ts
  src/army/everchosen/abilities.ts
  src/army/flesh_eater_courts/abilities.ts
  src/army/fyreslayers/abilities.ts
  src/army/gloomspite/abilities.ts
  src/army/gutbusters/abilities.ts
  src/army/idoneth/abilities.ts
  src/army/ironjawz/abilities.ts
  src/army/kharadron_overlords/abilities.ts
  src/army/khorne/abilities.ts
  src/army/legions_of_azgorh/abilities.ts
  src/army/legions_of_nagash/abilities.ts
  src/army/malign_sorcery/realmscape_features.ts
  src/army/nighthaunt/abilities.ts
  src/army/nurgle/abilities.ts
  src/army/sample_army/abilities.ts
  src/army/seraphon/abilities.ts
  src/army/skaven/abilities.ts
  src/army/slaanesh/abilities.ts
  src/army/slaves_to_darkness/abilities.ts
  src/army/stormcast_eternals/abilities.ts
  src/army/sylvaneth/abilities.ts
  src/army/tamurkhans_horde/abilities.ts
  src/army/tzeentch/abilities.ts
  src/components/info/reminders.tsx
  src/meta/game_structure.ts
  src/tests/utils.test.ts
  src/types/army.ts
  src/types/data.ts
  src/utils/addToGame.ts
  src/utils/processGame.ts
  src/utils/processReminders.ts
Labels: enhancement

#215 More performance tweaks
  src/components/App.tsx
  src/components/info/reminders.tsx
  src/components/input/ally_armies.tsx
  src/components/input/ally_army_builder.tsx
  src/components/input/army_builder.tsx
  src/components/input/toolbar.tsx
  src/components/print/print.tsx
  src/ducks/army.ts
  src/ducks/factionNames.ts
  src/ducks/realmscape.ts
  src/ducks/selections.ts
  src/types/store.ts
  src/utils/processGame.ts
  src/utils/processReminders.ts
Labels: enhancement

#216 Update print.tsx
  src/components/print/print.tsx
Labels: enhancement

#218 Add KoS types (fixes #207)
  src/army/slaanesh/units.ts
Labels: rule updates

#219 Add Beasts of Chaos (fixes #197)
  README.md
  clean.js
  src/army/beasts_of_chaos/abilities.ts
  src/army/beasts_of_chaos/allegiances.ts
  src/army/beasts_of_chaos/artifacts.ts
  src/army/beasts_of_chaos/endless_spells.ts
  src/army/beasts_of_chaos/index.ts
  src/army/beasts_of_chaos/spells.ts
  src/army/beasts_of_chaos/traits.ts
  src/army/beasts_of_chaos/units.ts
  src/meta/army_list.ts
  src/meta/factions.ts
Labels: new army

#221 Update Beasts of Chaos allegiances.ts
  src/army/beasts_of_chaos/allegiances.ts
Labels: rule updates

#226 Update endless_spells.ts
  CONTRIBUTING.md
  README.md
  src/army/fyreslayers/endless_spells.ts
  src/army/fyreslayers/units.ts
  src/components/print/print.tsx
Labels: rule updates

#227 Idoneth Deepkin Lore Spells (closes #160)
  README.md
  src/army/flesh_eater_courts/endless_spells.ts
  src/army/idoneth/endless_spells.ts
  src/army/idoneth/spells.ts
  src/army/legions_of_azgorh/endless_spells.ts
  src/army/legions_of_nagash/endless_spells.ts
  src/army/seraphon/endless_spells.ts
Labels: rule updates

#230 * Adding in Forbidden Power elements. (Fixes #192).
  src/army/generic/commands.ts
  src/army/generic/endless_spells.ts
  src/army/generic/index.ts
  src/army/generic/realm_artifacts.ts
  src/army/generic/realm_spells.ts
  src/army/generic/realmscape_commands.ts
  src/army/generic/realmscape_features.ts
  src/army/generic/realmscape_spells.ts
  src/army/generic/scenery.ts
  src/army/generic/spells.ts
  src/army/generic/triumphs.ts
  src/army/malign_sorcery/index.ts
  src/components/input/army_builder.tsx
  src/tests/utils.test.ts
  src/types/army.ts
  src/types/realmscapes.ts
  src/utils/getArmy.ts
  src/utils/processReminders.ts
Labels: enhancement, rule updates

#238 Update to realm spells.
  src/army/generic/index.ts
  src/army/generic/realm_spells.ts
  src/army/generic/realmscape_spells.ts
  src/utils/getArmy.ts
Labels: rule updates

#240 Update all dependencies (fixes #239)
  package.json
  src/index.tsx
  yarn.lock
Labels: bug, enhancement

#242 Add Print warning to IE (#236)
  package.json
  src/components/info/card.tsx
  src/components/input/ally_army_builder.tsx
  src/components/input/select.tsx
  src/components/input/toolbar.tsx
  src/utils/withSelect.ts
  yarn.lock
Labels: bug, enhancement

#244 * Fixed linkages with Nurgle/Tamurkhan units.
  src/army/nurgle/index.ts
  src/army/tamurkhans_horde/index.ts
Labels: rule updates

#243 Added Grand Alliance selections for faction choices.
  src/army/grand_alliances/chaos/index.ts
  src/army/grand_alliances/chaos/units.ts
  src/army/grand_alliances/death/index.ts
  src/army/grand_alliances/death/units.ts
  src/army/grand_alliances/destruction/index.ts
  src/army/grand_alliances/destruction/units.ts
  src/army/grand_alliances/order/index.ts
  src/army/grand_alliances/order/units.ts
  src/meta/army_list.ts
  src/meta/factions.ts
Labels: new army

#251 General clean up and fixes for Idoneth Deepkin
  src/army/idoneth/allegiances.ts
  src/army/idoneth/scenery.ts
  src/army/idoneth/spells.ts
  src/army/idoneth/traits.ts
Labels: rule updates

#250 Update chaos
  src/army/grand_alliances/chaos/artifacts.ts
  src/army/grand_alliances/chaos/traits.ts
  src/army/grand_alliances/chaos/units.ts
  src/army/grand_alliances/death/artifacts.ts
  src/army/grand_alliances/death/traits.ts
  src/army/grand_alliances/death/units.ts
  src/army/grand_alliances/destruction/artifacts.ts
  src/army/grand_alliances/order/artifacts.ts
  src/army/grand_alliances/order/traits.ts
  src/army/grand_alliances/order/units.ts
  src/army/khorne/units.ts
  src/army/nighthaunt/units.ts
  src/army/nurgle/artifacts.ts
  src/army/nurgle/units.ts
  src/army/slaanesh/units.ts
  src/army/slaves_to_darkness/abilities.ts
  src/army/slaves_to_darkness/artifacts.ts
  src/army/slaves_to_darkness/traits.ts
  src/army/slaves_to_darkness/units.ts
  src/army/tzeentch/units.ts
  src/meta/alliances.ts
  src/utils/chaosUtils.ts
Labels: enhancement, rule updates

#253 Update chaos
  src/army/grand_alliances/chaos/units.ts
Labels: rule updates

#254 General cleanup for Fyreslayers
  src/army/fyreslayers/abilities.ts
  src/army/fyreslayers/endless_spells.ts
  src/army/fyreslayers/scenery.ts
Labels: rule updates

#255 IE10+ and Edge print bugs (#236)
  src/components/info/reminders.css
  src/components/info/reminders.tsx
  src/components/input/toolbar.tsx
Labels: bug

#256 Update dependencies, add key
  package.json
  src/components/info/reminders.tsx
  yarn.lock
Labels: enhancement

#257 Condense logic around Chaos Units, refactor processGame
  src/army/khorne/units.ts
  src/army/nurgle/units.ts
  src/army/slaanesh/units.ts
  src/army/slaves_to_darkness/units.ts
  src/army/tzeentch/units.ts
  src/meta/alliances.ts
  src/utils/addToGame.ts
  src/utils/chaosUtils.ts
  src/utils/processGame.ts
Labels: enhancement

#262 Added in missing magic & spell details for Legion of Azgorh Daemonsmiths
  README.md
  src/army/legions_of_azgorh/units.ts
Labels: rule updates

#264 Add scenery
  src/army/generic/index.ts
  src/army/generic/scenery.ts
  src/types/terrain.ts
Labels: rule updates

#266 Add Commands and Triumphs (fixes #229)
  package.json
  src/army/generic/commands.ts
  src/army/generic/index.ts
  src/army/generic/realmscape_commands.ts
  src/army/generic/realmscape_spells.ts
  src/army/generic/triumphs.ts
  src/components/info/reminders.tsx
  src/components/input/army_builder.tsx
  src/components/print/print.tsx
  src/ducks/army.ts
  src/ducks/selections.ts
  src/tests/__mock.ts
  src/tests/getArmy.test.ts
  src/tests/processReminders.test.ts
  src/tests/utils.test.ts
  src/types/army.ts
  src/types/data.ts
  src/types/selections.ts
  src/utils/getArmy.ts
  src/utils/realmUtils.ts
  yarn.lock
Labels: enhancement

#267 Hiding selectors (fixes #265)
  src/components/info/card.tsx
  src/components/info/reminders.tsx
  src/components/info/visibilityToggle.tsx
  src/components/input/army_builder.tsx
  src/components/input/select_realmscape.tsx
  src/ducks/index.ts
  src/ducks/visibility.ts
  src/index.tsx
  src/types/store.ts
Labels: enhancement

#269 Update Gloomtide Shipwreck name
  src/army/idoneth/abilities.ts
  src/army/idoneth/scenery.ts
Labels: rule updates

#276 Update BoC unit rules (fixes #274)
  src/army/beasts_of_chaos/units.ts
Labels: rule updates

#281 Add Mutalith Vortex Beast (fixes #280)
  clean.js
  src/army/grand_alliances/chaos/units.ts
  src/army/tzeentch/units.ts
Labels: rule updates

#286 Add FEC Endless Spells and Spells
  src/army/flesh_eater_courts/endless_spells.ts
  src/army/flesh_eater_courts/spells.ts
  src/army/flesh_eater_courts/traits.ts
Labels: rule updates

#288 Update FEC and Slaanesh spells (fixes #287)
  src/army/flesh_eater_courts/spells.ts
  src/army/slaanesh/endless_spells.ts
Labels: rule updates

#290 Mobile updates, CSS changes (fixes #277)
  package.json
  public/img/logo.png
  public/img/logo_noURL.png
  src/army/everchosen/units.ts
  src/army/legions_of_grief/units.ts
  src/army/lethisian_army/units.ts
  src/army/nighthaunt/units.ts
  src/army/slaves_to_darkness/units.ts
  src/components/info/card.css
  src/components/info/card.tsx
  src/components/info/reminder.tsx
  src/components/info/reminders.css
  src/components/info/reminders.tsx
  src/components/info/visibilityToggle.tsx
  src/components/input/ally_army_builder.tsx
  src/components/input/army_builder.tsx
  src/components/page/header.css
  src/components/page/header.tsx
  src/ducks/visibility.ts
  src/types/store.ts
  src/utils/filterUtils.ts
  src/utils/mapSizesToProps.ts
  yarn.lock
Labels: enhancement

#292 Adding Wanderers for #289
  src/army/mercenary_companies/allegiances.ts
  src/army/mercenary_companies/artifacts.ts
  src/army/mercenary_companies/endless_spells.ts
  src/army/mercenary_companies/scenery.ts
  src/army/mercenary_companies/spells.ts
  src/army/mercenary_companies/traits.ts
  src/army/wanderers/abilities.ts
  src/army/wanderers/artifacts.ts
  src/army/wanderers/index.ts
  src/army/wanderers/traits.ts
  src/army/wanderers/units.ts
  src/meta/army_list.ts
  src/meta/factions.ts
Labels: new army

#294 More mobile styling updates
  src/components/info/card.css
  src/components/info/card.tsx
  src/components/input/army_builder.tsx
  src/components/input/cardOrder.ts
Labels: enhancement

#295 Mobile UI Improvements (added animations)
  package.json
  src/components/info/card.css
  src/components/info/card.tsx
  src/components/info/reminder.tsx
  src/components/info/reminders.css
  src/components/info/reminders.tsx
  src/components/input/ally_army_builder.tsx
  src/components/input/army_builder.css
  src/components/input/army_builder.tsx
  src/components/page/header.css
  src/components/page/header.tsx
  src/css/animations.css
  src/css/index.css
  src/index.css
  src/index.tsx
  yarn.lock
Labels: enhancement, ui

#312 Update spells.ts (fixes #309)
  src/army/stormcast_eternals/spells.ts
Labels: rule updates

#314 Adding Bonesplitterz (Fixes #279)
  src/army/bonesplitterz/abilities.ts
  src/army/bonesplitterz/artifacts.ts
  src/army/bonesplitterz/index.ts
  src/army/bonesplitterz/spells.ts
  src/army/bonesplitterz/traits.ts
  src/army/bonesplitterz/units.ts
  src/meta/army_list.ts
  src/meta/factions.ts
Labels: new army

#313 Adding for #282
  find
  src/army/grand_alliances/chaos/units.ts
Labels: rule updates

#316 Added Monstrous Arcanum (fixes #275)
  src/army/grand_alliances/chaos/units.ts
  src/army/grand_alliances/destruction/units.ts
  src/army/grand_alliances/order/units.ts
  src/army/nurgle/units.ts
  src/army/slaanesh/units.ts
  src/army/slaves_to_darkness/units.ts
  src/army/tzeentch/units.ts
Labels: rule updates

#315 Typo fix
  src/army/bonesplitterz/units.ts
Labels: rule updates

#323 Fixes #318
  src/components/info/reminder.tsx
Labels: bug
