Repository daviseford/aos-reminders, pull requests merged in 2019-07, with the labels that each got.

#75 Add Tzeentch
  clean.js
  package.json
  src/army/dispossessed/traits.ts
  src/army/dispossessed/units.ts
  src/army/seraphon/units.ts
  src/army/skaven/artifacts.ts
  src/army/skaven/units.ts
  src/army/sylvaneth/units.ts
  src/army/tzeentch/abilities.ts
  src/army/tzeentch/artifacts.ts
  src/army/tzeentch/index.ts
  src/army/tzeentch/traits.ts
  src/army/tzeentch/units.ts
  src/meta/army_list.ts
  src/meta/factions.ts
  yarn.lock
Labels: new army

#76 Update print styles (fixes #71)
  clean.js
  src/components/info/reminders.css
  src/index.css
Labels: enhancement

#78 Distinguish traits and artifacts
  clean.js
  src/components/info/reminders.tsx
  src/components/print/print.tsx
  src/meta/turn_structure.ts
  src/types/army.ts
  src/utils/getArmy.ts
  src/utils/processGame.ts
  src/utils/processReminders.ts
Labels: enhancement

#81 GHB 2019 FEC Errata
  clean.js
  src/army/flesh_eater_courts/traits.ts
Labels: rule updates

#82 Kharadron Overlords
  README.md
  src/army/kharadron_overlords/abilities.ts
  src/army/kharadron_overlords/artifacts.ts
  src/army/kharadron_overlords/index.ts
  src/army/kharadron_overlords/traits.ts
  src/army/kharadron_overlords/units.ts
  src/meta/army_list.ts
  src/meta/factions.ts
Labels: new army

#86 Added Death Battletome: Nighthaunt data
  README.md
  src/army/nighthaunt/abilities.ts
  src/army/nighthaunt/artifacts.ts
  src/army/nighthaunt/index.ts
  src/army/nighthaunt/traits.ts
  src/army/nighthaunt/units.ts
  src/meta/army_list.ts
  src/meta/factions.ts
Labels: new army

#88 Refine clean.js
  clean.js
  src/army/gloomspite/abilities.ts
  src/army/gloomspite/traits.ts
  src/army/gloomspite/units.ts
  src/army/grand_alliances/destruction/artifacts.ts
  src/army/idoneth/artifacts.ts
  src/army/idoneth/units.ts
  src/army/ironjawz/units.ts
  src/army/kharadron_overlords/traits.ts
  src/army/kharadron_overlords/units.ts
  src/army/malign_sorcery/realmscape_features.ts
  src/army/nighthaunt/abilities.ts
  src/army/nighthaunt/traits.ts
  src/army/seraphon/units.ts
  src/army/skaven/units.ts
  src/army/sylvaneth/units.ts
  src/army/tzeentch/artifacts.ts
Labels: enhancement

#89 Add Khorne (fixes #85)
  src/army/khorne/abilities.ts
  src/army/khorne/artifacts.ts
  src/army/khorne/index.ts
  src/army/khorne/traits.ts
  src/army/khorne/units.ts
  src/meta/army_list.ts
  src/meta/factions.ts
Labels: new army

#91 Update Khorne rules to 2019 Battletome (fixes #90)
  README.md
  src/army/beastclaw_raiders/units.ts
  src/army/dispossessed/units.ts
  src/army/flesh_eater_courts/abilities.ts
  src/army/flesh_eater_courts/traits.ts
  src/army/flesh_eater_courts/units.ts
  src/army/gloomspite/units.ts
  src/army/idoneth/units.ts
  src/army/ironjawz/abilities.ts
  src/army/ironjawz/units.ts
  src/army/kharadron_overlords/traits.ts
  src/army/kharadron_overlords/units.ts
  src/army/khorne/abilities.ts
  src/army/khorne/artifacts.ts
  src/army/khorne/index.ts
  src/army/khorne/traits.ts
  src/army/khorne/units.ts
  src/army/nighthaunt/abilities.ts
  src/army/nighthaunt/units.ts
  src/army/seraphon/units.ts
  src/army/skaven/units.ts
  src/army/sylvaneth/units.ts
  src/army/tzeentch/units.ts
  src/components/info/reminders.tsx
  src/meta/game_structure.ts
  src/types/army.ts
  src/types/data.ts
  src/utils/addToGame.ts
  src/utils/processGame.ts
  src/utils/processReminders.ts
Labels: rule updates

#92 Adding Legions of Nagash
  .gitignore
  README.md
  src/army/legions_of_nagash/abilities.ts
  src/army/legions_of_nagash/artifacts.ts
  src/army/legions_of_nagash/index.ts
  src/army/legions_of_nagash/traits.ts
  src/army/legions_of_nagash/units.ts
  src/meta/army_list.ts
  src/meta/factions.ts
Labels: new army

#93 Update LoN Abilities
  clean.js
  src/army/legions_of_nagash/abilities.ts
  src/army/legions_of_nagash/artifacts.ts
Labels: enhancement

#97 Add support for allies (fixes #37)
  package.json
  src/army/dispossessed/units.ts
  src/components/App.tsx
  src/components/info/reminders.tsx
  src/components/input/army_builder.tsx
  src/components/input/toolbar.tsx
  src/components/print/button.tsx
  src/components/print/print.tsx
  src/index.tsx
  src/types/data.ts
  src/types/selections.ts
  src/utils/analytics.ts
  src/utils/getArmy.ts
  src/utils/processGame.ts
  src/utils/processReminders.ts
  yarn.lock
Labels: enhancement

#100 Update Deathly Invocation ability (fixes #99 )
  src/army/legions_of_nagash/units.ts
Labels: rule updates

#102 Update Ironjawz rules (fixes #101 )
  src/army/ironjawz/units.ts
Labels: rule updates

#105 Add ability to hide rules (fixes #96)
  package.json
  src/components/info/reminders.tsx
  yarn.lock
Labels: enhancement

#114 Implement redux (fixes #104)
  package.json
  src/components/App.tsx
  src/components/info/card.tsx
  src/components/info/reminders.tsx
  src/components/input/ally_army_builder.tsx
  src/components/input/army_builder.tsx
  src/components/input/select_realmscape.tsx
  src/components/input/toolbar.tsx
  src/components/page/footer.tsx
  src/components/page/header.tsx
  src/components/print/print.tsx
  src/ducks/army.ts
  src/ducks/factionNames.ts
  src/ducks/index.ts
  src/ducks/realmscape.ts
  src/ducks/selections.ts
  src/index.tsx
  src/utils/getArmy.ts
  src/utils/withSelect.ts
  yarn.lock
Labels: enhancement

#115 Update LoN units.ts
  src/army/legions_of_nagash/units.ts
Labels: enhancement

#118 Add favicon (fixes #117)
  public/favicon.ico
  public/index.html
  public/manifest.json
Labels: enhancement

#103 Add Stormcast Eternals (fixes #106)
  README.md
  src/army/stormcast_eternals/abilities.ts
  src/army/stormcast_eternals/artifacts.ts
  src/army/stormcast_eternals/index.ts
  src/army/stormcast_eternals/traits.ts
  src/army/stormcast_eternals/units.ts
  src/meta/army_list.ts
  src/meta/factions.ts
Labels: in progress

#120 Add Donate button (fixes #107)
  package.json
  src/components/info/card.tsx
  src/components/info/donate.tsx
  src/components/input/select_realmscape.tsx
  src/components/input/toolbar.tsx
  src/components/page/footer.tsx
  yarn.lock
Labels: enhancement

#121 Fix hiding rules (fixes #96)
  src/components/info/donate.tsx
  src/components/info/reminders.tsx
Labels: bug

#123 Update Seraphon units.ts (fixes #122)
  src/army/seraphon/units.ts
Labels: rule updates

#125 Add nurgle (Fixes: #109)
  src/army/nurgle/abilities.ts
  src/army/nurgle/artifacts.ts
  src/army/nurgle/index.ts
  src/army/nurgle/spells.ts
  src/army/nurgle/traits.ts
  src/army/nurgle/units.ts
  src/meta/army_list.ts
  src/meta/factions.ts
Labels: new army

#126 SC fixes #124
  src/army/stormcast_eternals/units.ts
Labels: rule updates

#130 Fixes #128 SCE Lord-Aquilor CA
  src/army/stormcast_eternals/units.ts
Labels: rule updates

#133 Fyreslayers fix
  src/army/fyreslayers/abilities.ts
Labels: rule updates

#138 Update Realmscape select (fixes #136)
  src/components/input/army_builder.tsx
  src/components/page/header.tsx
  src/components/print/print.tsx
  src/ducks/realmscape.ts
  src/utils/processReminders.ts
  src/utils/withSelect.ts
Labels: bug

#140 Update header.tsx (fixes #139)
  src/components/page/header.tsx
Labels: enhancement
