Repository daviseford/aos-reminders, pull requests merged in 2019-11, with the labels that each got.

#667 Dark mode (fixes #628)
  package.json
  public/index.html
  src/api/subscriptionApi.ts
  src/components/App.tsx
  src/components/helpers/link.tsx
  src/components/helpers/suspenseFallbacks.tsx
  src/components/info/banners/app_banner.tsx
  src/components/info/card.tsx
  src/components/info/donate.tsx
  src/components/info/offline.tsx
  src/components/info/reminder.tsx
  src/components/info/visibilityToggle.tsx
  src/components/input/ally_army_builder.tsx
  src/components/input/generic_button.tsx
  src/components/input/importPdf/drop_zone.tsx
  src/components/input/savedArmies/delete_army_modal.tsx
  src/components/input/savedArmies/loaded_army_header.tsx
  src/components/input/savedArmies/save_army_btn.tsx
  src/components/input/savedArmies/saved_army_card.tsx
  src/components/input/savedArmies/saved_army_table.tsx
  src/components/input/savedArmies/show_saved_armies_btn.tsx
  src/components/input/savedArmies/update_army_btn.tsx
  src/components/input/select.tsx
  src/components/input/toolbar/add_ally_btn.tsx
  src/components/input/toolbar/import_army_btn.tsx
  src/components/page/contact.tsx
  src/components/page/footer.tsx
  src/components/page/homeHeader.tsx
  src/components/page/navbar.tsx
  src/components/page/navbar_wrapper.tsx
  src/components/payment/pricingPlans.tsx
  src/components/print/pdfButton.tsx
  src/components/print/pdfModal.tsx
  src/components/routes/Home.tsx
  src/components/routes/Profile.tsx
  src/components/routes/Subscribe.tsx
  src/context/useSavedArmies.tsx
  src/context/useTheme.tsx
  src/css/index.scss
  src/css/theme.scss
  src/index.tsx
  src/theme/dark.ts
  src/theme/helperClasses.ts
  src/theme/light.ts
  src/types/subscription.ts
  src/types/theme.ts
  src/utils/localStore.ts
  yarn.lock
Labels: subscriber feature, ui

#669 Hotfix: Revert changes to favoriteFaction
  src/api/subscriptionApi.ts
  src/context/useSavedArmies.tsx
Labels: bug, subscriber feature

#671 Battlescribe and WSB import fixes
  src/army/skaven/artifacts.ts
  src/army/slaanesh/artifacts.ts
  src/tests/battlescribe/battlescribeHTML.test.ts
  src/tests/fixtures/battlescribe/html/Nurgle2.html
  src/tests/fixtures/warscroll/json/1572660547365-Warscroll_Builder.json
  src/tests/fixtures/warscroll/json/1572694928061-Warscroll_Builder.json
  src/tests/fixtures/warscroll/json/1572695046339-Warscroll_Builder.json
  src/tests/warscroll/warscrollJson.test.ts
  src/utils/battlescribe/getters.ts
Labels: battlescribe, warscroll-builder

#668 Warn about ambiguous imports
  src/components/input/importPdf/drop_container.tsx
  src/tests/azyr/getAzyrArmy.test.ts
  src/tests/fixtures/azyr/json/Fyreslayers3.json
  src/tests/fixtures/azyr/json/Stormcast5.json
  src/tests/fixtures/azyr/pdf/Fyreslayers3.pdf
  src/tests/fixtures/azyr/pdf/Stormcast5.pdf
  src/types/import.ts
  src/utils/import/ambiguousSelections.ts
  src/utils/import/index.ts
  src/utils/import/options.ts
  src/utils/import/warnings.ts
Labels: azyr

#672 Update Modals with Dark theme
  package.json
  src/components/helpers/suspenseFallbacks.tsx
  src/components/info/banners/app_banner.tsx
  src/components/input/cancellation_modal.tsx
  src/components/input/savedArmies/delete_army_modal.tsx
  src/components/input/savedArmies/save_army_modal.tsx
  src/components/input/savedArmies/update_name_modal.tsx
  src/components/page/genericModal.tsx
  src/components/print/pdfModal.tsx
  src/components/routes/Home.tsx
  src/components/routes/Profile.tsx
  src/components/routes/Subscribe.tsx
  src/css/index.scss
  src/theme/dark.ts
  src/theme/helperClasses.ts
  src/theme/light.ts
  src/theme/modalStyle.ts
  src/types/theme.ts
  yarn.lock
Labels: ui

#674 Fix OBR Legions not importing correctly (fixes #673)
  src/components/info/banners/app_banner.tsx
  src/components/info/banners/notification_banner.tsx
  src/tests/azyr/azyrImport.test.ts
  src/tests/azyr/getAzyrArmy.test.ts
  src/tests/fixtures/azyr/json/OBR1.json
  src/utils/azyr/azyrPdf.ts
Labels: azyr

#675 Add Ossiarch Bonereapers
  src/army/gloomspite/units.ts
  src/army/ironjawz/spells.ts
  src/army/ogor_mawtribes/spells.ts
  src/army/ossiarch_bonereapers/abilities.ts
  src/army/ossiarch_bonereapers/allegiances.ts
  src/army/ossiarch_bonereapers/artifacts.ts
  src/army/ossiarch_bonereapers/index.ts
  src/army/ossiarch_bonereapers/spells.ts
  src/army/ossiarch_bonereapers/traits.ts
  src/army/ossiarch_bonereapers/units.ts
  src/army/skaven/units.ts
  src/tests/azyr/azyrImport.test.ts
  src/tests/azyr/getAzyrArmy.test.ts
  src/tests/battlescribe/battlescribeHTML.test.ts
  src/tests/fixtures/azyr/json/Khorne4.json
  src/tests/fixtures/azyr/json/Nighthaunt2.json
  src/tests/fixtures/azyr/json/OBR2.json
  src/tests/fixtures/azyr/json/OgorMawtribes1.json
  src/tests/fixtures/azyr/json/OgorMawtribes2.json
  src/tests/fixtures/azyr/json/Stormcast6.json
  src/tests/fixtures/battlescribe/html/Gloomspite3.html
  src/tests/fixtures/warscroll/json/1572735282204-Warscroll_Builder.json
  src/tests/warscroll/warscrollJson.test.ts
  src/utils/azyr/azyrPdf.ts
  src/utils/battlescribe/parseHTML.ts
  src/utils/import/options.ts
  src/utils/import/warnings.ts
Labels: rule updates

#676 Add Ogor Mawtribes (fixes #625) (fixes #510)
  package.json
  public/img/dark_mode1.gif
  public/img/dark_mode1.mp4
  src/army/ogor_mawtribes/abilities.ts
  src/army/ogor_mawtribes/allegiances.ts
  src/army/ogor_mawtribes/artifacts.ts
  src/army/ogor_mawtribes/endless_spells.ts
  src/army/ogor_mawtribes/index.ts
  src/army/ogor_mawtribes/scenery.ts
  src/army/ogor_mawtribes/traits.ts
  src/army/ogor_mawtribes/units.ts
  src/components/info/banners/app_banner.tsx
  src/components/info/banners/notification_banner.tsx
  src/components/info/banners/update_banner.tsx
  src/components/routes/Subscribe.tsx
  yarn.lock
Labels: rule updates

#677 Mark mount traits and display them as such in the reminder
  src/army/fyreslayers/traits.ts
  src/army/ironjawz/traits.ts
  src/army/ogor_mawtribes/traits.ts
  src/army/stormcast_eternals/traits.ts
  src/tests/azyr/getAzyrArmy.test.ts
  src/tests/warscroll/warscrollPdf.test.ts
  src/types/data.ts
  src/utils/import/options.ts
  src/utils/textUtils.ts
Labels: enhancement

#678 Better service worker
  src/components/info/banners/notification_banner.tsx
  src/components/info/banners/update_banner.tsx
  src/components/input/generic_button.tsx
  src/context/useAppStatus.tsx
  src/index.tsx
  src/serviceWorker.ts
Labels: maintenance

#683 Mirrorshield fix
  src/army/stormcast_eternals/artifacts.ts
  src/tests/fixtures/warscroll/json/1572905242205-Warscroll_Builder.json
  src/tests/warscroll/warscrollJson.test.ts
  src/utils/import/options.ts
Labels: rule updates

#684 Dark mode updates
  package.json
  src/context/useTheme.tsx
  yarn.lock
Labels: maintenance, ui

#685 Remove BCR and Gutbusters
  src/army/beastclaw_raiders/abilities.ts
  src/army/beastclaw_raiders/artifacts.ts
  src/army/beastclaw_raiders/index.ts
  src/army/beastclaw_raiders/traits.ts
  src/army/beastclaw_raiders/units.ts
  src/army/gutbusters/abilities.ts
  src/army/gutbusters/index.ts
  src/army/gutbusters/traits.ts
  src/army/gutbusters/units.ts
  src/meta/army_list.ts
  src/meta/factions.ts
  src/tests/processReminders.test.ts
  src/utils/import/options.ts
Labels: rule updates

#686 Update Big Waagh ability text
  src/army/big_waaagh/abilities.ts
  src/army/ironjawz/allegiances.ts
  src/army/ironjawz/traits.ts
  src/army/sylvaneth/scenery.ts
  src/army/sylvaneth/units.ts
Labels: rule updates

#687 Import fixes for all three sources
  package.json
  src/army/fyreslayers/allegiances.ts
  src/army/nighthaunt/units.ts
  src/tests/azyr/getAzyrArmy.test.ts
  src/tests/battlescribe/battlescribeHTML.test.ts
  src/tests/fixtures/azyr/json/CoS5.json
  src/tests/fixtures/battlescribe/html/Fyreslayers3.html
  src/tests/fixtures/battlescribe/html/Ironjawz1.html
  src/tests/fixtures/battlescribe/html/Ironjawz2.html
  src/tests/fixtures/battlescribe/html/Nighthaunt2.html
  src/tests/fixtures/battlescribe/html/Nighthaunt3.html
  src/tests/fixtures/warscroll/json/1573012088615-Warscroll_Builder.json
  src/tests/fixtures/warscroll/json/1573018890027-Warscroll_Builder.json
  src/tests/fixtures/warscroll/json/1573020637936-Warscroll_Builder.json
  src/tests/fixtures/warscroll/json/1573045302823-Warscroll_Builder.json
  src/tests/warscroll/warscrollJson.test.ts
  src/utils/battlescribe/checks.ts
  src/utils/battlescribe/getters.ts
  src/utils/import/options.ts
  yarn.lock
Labels: azyr, battlescribe, warscroll-builder

#690 Fix hidden rules appearing PDF + Import fixes
  package.json
  src/army/bonesplitterz/units.ts
  src/components/info/reminder.tsx
  src/components/routes/Home.tsx
  src/tests/azyr/azyrImport.test.ts
  src/tests/azyr/getAzyrArmy.test.ts
  src/tests/battlescribe/battlescribeHTML.test.ts
  src/tests/fixtures/azyr/json/IDK2.json
  src/tests/fixtures/battlescribe/html/Gloomspite4.html
  src/tests/utils.test.ts
  src/utils/azyr/azyrPdf.ts
  src/utils/battlescribe/parseHTML.ts
  src/utils/pdf/generate/generatePdf.ts
  src/utils/pdf/generate/getVisibleReminders.ts
  src/utils/reminderUtils.ts
  yarn.lock
Labels: azyr, battlescribe, bug, pdf

#691 Add Big Rukk battalion
  src/army/bonesplitterz/allegiances.ts
  src/army/bonesplitterz/artifacts.ts
  src/army/bonesplitterz/units.ts
  src/tests/fixtures/warscroll/json/1573142427791-Warscroll_Builder.json
  src/tests/fixtures/warscroll/json/1573144291799-Warscroll_Builder.json
  src/tests/warscroll/warscrollJson.test.ts
Labels: rule updates

#692 Fix Arch Sorcerer import
  src/tests/fixtures/warscroll/json/1573145524404-Warscroll_Builder.json
  src/tests/warscroll/warscrollJson.test.ts
  src/utils/import/options.ts
Labels: warscroll-builder

#693 Amethyst Glow typo fix
  src/army/legions_of_grief/traits.ts
  src/tests/azyr/getAzyrArmy.test.ts
  src/tests/fixtures/azyr/json/LoG3.json
Labels: rule updates

#694 Add ability to share armies via url (fixes #562)
  package.json
  src/api/preferenceApi.ts
  src/components/App.tsx
  src/components/helpers/suspenseFallbacks.tsx
  src/components/input/savedArmies/save_army_btn.tsx
  src/components/input/savedArmies/save_army_modal.tsx
  src/components/input/savedArmies/show_saved_armies_btn.tsx
  src/components/input/shareArmy/share_army_btn.tsx
  src/components/input/shareArmy/share_army_modal.tsx
  src/components/input/toolbar/toolbar.tsx
  src/context/useSavedArmies.tsx
  src/tests/azyr/getAzyrArmy.test.ts
  src/tests/fixtures/azyr/json/IDK3.json
  src/theme/dark.ts
  src/theme/light.ts
  src/types/savedArmy.ts
  src/types/theme.ts
  src/utils/handleQueryParams.ts
  src/utils/loadArmyFromLink.ts
  yarn.lock
Labels: enhancement

#696 Quick updates
  src/components/info/banners/app_banner.tsx
  src/components/routes/Home.tsx
  src/components/routes/Subscribe.tsx
  src/css/index.scss
Labels: ui

#697 Update useTheme.tsx
  src/context/useTheme.tsx
  src/tests/fixtures/warscroll/json/1573172812429-Warscroll_Builder.json
  src/tests/fixtures/warscroll/json/1573174872898-Warscroll_Builder.json
  src/tests/warscroll/warscrollJson.test.ts
  src/utils/import/options.ts
Labels: ui

#698 Yet another dark mode bugfix
  package.json
  src/context/useSubscription.tsx
  src/context/useTheme.tsx
  src/tests/fixtures/warscroll/json/1573208101434-Warscroll_Builder.json
  src/tests/warscroll/warscrollJson.test.ts
  yarn.lock
Labels: ui

#700 Add a bunch of missing Skaven spells
  src/army/skaven/units.ts
  src/tests/battlescribe/battlescribeHTML.test.ts
  src/tests/fixtures/battlescribe/html/Fyreslayers4.html
  src/tests/fixtures/battlescribe/html/Skaven3.html
  src/utils/battlescribe/getters.ts
Labels: rule updates

#702 Fixed favorite faction overriding linked army faction
  src/army/fyreslayers/allegiances.ts
  src/components/page/homeHeader.tsx
  src/tests/battlescribe/battlescribeHTML.test.ts
  src/tests/fixtures/warscroll/json/1573252116567-Warscroll_Builder.json
  src/tests/fixtures/warscroll/json/1573254186379-Warscroll_Builder.json
  src/tests/warscroll/warscrollJson.test.ts
  src/utils/handleQueryParams.ts
  src/utils/import/options.ts
  src/utils/warscroll/getWarscrollArmy.ts
Labels: bug

#704 Add Tomb Kings (fixes #493)
  src/army/tomb_kings/abilities.ts
  src/army/tomb_kings/index.ts
  src/army/tomb_kings/units.ts
  src/meta/army_list.ts
  src/meta/factions.ts
Labels: new army

#706 Update endpoints
  src/api/subscriptionApi.ts
  src/utils/import/options.ts
Labels: maintenance

#707 Revert a dark mode change
  src/context/useSubscription.tsx
  src/context/useTheme.tsx
  src/tests/battlescribe/battlescribeHTML.test.ts
  src/tests/fixtures/battlescribe/html/Stormcast5.html
  src/utils/import/options.ts
Labels: battlescribe, ui

#708 Add support for Tomb Kings Battlescribe import
  src/tests/battlescribe/battlescribeHTML.test.ts
  src/tests/fixtures/battlescribe/html/TombKings1.html
  src/utils/battlescribe/getters.ts
  src/utils/import/options.ts
Labels: battlescribe

#709 Added another Big Waaagh test file
  src/tests/battlescribe/battlescribeHTML.test.ts
  src/tests/fixtures/battlescribe/html/BigWaaagh3.html
Labels: battlescribe

#712 Add wound allocation
  src/army/beasts_of_chaos/artifacts.ts
  src/army/cities_of_sigmar/units.ts
  src/army/daughters_of_khaine/abilities.ts
  src/army/flesh_eater_courts/units.ts
  src/army/generic/realm_artifacts.ts
  src/army/generic/realmscape_spells.ts
  src/army/gloomspite/artifacts.ts
  src/army/grand_alliances/destruction/artifacts.ts
  src/army/grand_alliances/destruction/units.ts
  src/army/grand_alliances/order/units.ts
  src/army/grand_host_of_nagash/units.ts
  src/army/idoneth/artifacts.ts
  src/army/khorne/artifacts.ts
  src/army/legions_of_nagash/units.ts
  src/army/nighthaunt/units.ts
  src/army/ogor_mawtribes/artifacts.ts
  src/army/ossiarch_bonereapers/spells.ts
  src/army/ossiarch_bonereapers/units.ts
  src/army/skaven/traits.ts
  src/army/slaanesh/units.ts
  src/army/slaves_to_darkness/units.ts
  src/army/sylvaneth/artifacts.ts
  src/army/sylvaneth/units.ts
  src/army/tamurkhans_horde/units.ts
Labels: rule updates

#711 Rules cleanup (wound allocation + consolidating common rules)
  src/army/beasts_of_chaos/units.ts
  src/army/big_waaagh/abilities.ts
  src/army/bonesplitterz/abilities.ts
  src/army/bonesplitterz/artifacts.ts
  src/army/bonesplitterz/traits.ts
  src/army/bonesplitterz/units.ts
  src/army/cities_of_sigmar/abilities.ts
  src/army/cities_of_sigmar/allegiances.ts
  src/army/cities_of_sigmar/artifacts.ts
  src/army/cities_of_sigmar/spells.ts
  src/army/cities_of_sigmar/traits.ts
  src/army/cities_of_sigmar/units.ts
  src/army/daughters_of_khaine/abilities.ts
  src/army/everchosen/units.ts
  src/army/flesh_eater_courts/units.ts
  src/army/fyreslayers/abilities.ts
  src/army/fyreslayers/units.ts
  src/army/generic/scenery.ts
  src/army/gloomspite/traits.ts
  src/army/gloomspite/units.ts
  src/army/grand_alliances/chaos/units.ts
  src/army/grand_alliances/destruction/artifacts.ts
  src/army/grand_alliances/destruction/units.ts
  src/army/grand_alliances/order/units.ts
  src/army/grand_host_of_nagash/units.ts
  src/army/greenskinz/units.ts
  src/army/idoneth/scenery.ts
  src/army/ironjawz/abilities.ts
  src/army/ironjawz/artifacts.ts
  src/army/ironjawz/spells.ts
  src/army/ironjawz/units.ts
  src/army/khorne/units.ts
  src/army/nurgle/units.ts
  src/army/ogor_mawtribes/allegiances.ts
  src/army/ogor_mawtribes/artifacts.ts
  src/army/ogor_mawtribes/units.ts
  src/army/ossiarch_bonereapers/abilities.ts
  src/army/ossiarch_bonereapers/allegiances.ts
  src/army/ossiarch_bonereapers/artifacts.ts
  src/army/ossiarch_bonereapers/scenery.ts
  src/army/ossiarch_bonereapers/spells.ts
  src/army/ossiarch_bonereapers/traits.ts
  src/army/ossiarch_bonereapers/units.ts
  src/army/seraphon/artifacts.ts
  src/army/seraphon/units.ts
  src/army/skaven/traits.ts
  src/army/slaanesh/units.ts
  src/army/slaves_to_darkness/units.ts
  src/army/stormcast_eternals/units.ts
  src/army/sylvaneth/artifacts.ts
  src/army/sylvaneth/units.ts
  src/army/tamurkhans_horde/units.ts
  src/army/tomb_kings/abilities.ts
  src/army/tomb_kings/units.ts
  src/army/tzeentch/traits.ts
  src/army/tzeentch/units.ts
  src/army/wanderers/artifacts.ts
  src/army/wanderers/units.ts
Labels: rule updates

#714 Rule cleanup
  src/army/beasts_of_chaos/scenery.ts
  src/army/beasts_of_chaos/units.ts
  src/army/bonesplitterz/units.ts
  src/army/cities_of_sigmar/units.ts
  src/army/daughters_of_khaine/units.ts
  src/tests/azyr/getAzyrArmy.test.ts
  src/tests/fixtures/azyr/json/BCR2.json
  src/tests/fixtures/warscroll/json/1573340651447-Warscroll_Builder.json
  src/tests/fixtures/warscroll/json/1573387764362-Warscroll_Builder.json
  src/tests/warscroll/warscrollJson.test.ts
  src/utils/import/options.ts
Labels: rule updates

#716 More rule cleanup
  src/army/beasts_of_chaos/units.ts
  src/army/dispossessed/units.ts
  src/army/flesh_eater_courts/units.ts
  src/army/fyreslayers/units.ts
  src/army/generic/effects.ts
  src/army/gloomspite/units.ts
  src/army/grand_alliances/chaos/units.ts
  src/army/grand_alliances/destruction/units.ts
  src/army/idoneth/units.ts
  src/army/ironjawz/units.ts
  src/army/kharadron_overlords/units.ts
  src/army/khorne/units.ts
  src/army/legions_of_nagash/units.ts
  src/army/slaves_to_darkness/units.ts
  src/army/tamurkhans_horde/units.ts
  src/army/tomb_kings/units.ts
Labels: rule updates

#717 Set 'Allegiances' card title per faction: credit @exonian
  package.json
  src/army/beasts_of_chaos/index.ts
  src/army/bonesplitterz/index.ts
  src/army/cities_of_sigmar/index.ts
  src/army/daughters_of_khaine/index.ts
  src/army/flesh_eater_courts/index.ts
  src/army/fyreslayers/index.ts
  src/army/idoneth/index.ts
  src/army/ironjawz/index.ts
  src/army/kharadron_overlords/index.ts
  src/army/khorne/index.ts
  src/army/ogor_mawtribes/index.ts
  src/army/ossiarch_bonereapers/index.ts
  src/army/sample_army/index.ts
  src/army/skaven/index.ts
  src/army/slaanesh/index.ts
  src/army/soulblight/index.ts
  src/army/stormcast_eternals/index.ts
  src/army/sylvaneth/index.ts
  src/components/input/army_builder_cards.ts
  src/ducks/army.ts
  src/types/army.ts
Labels: ui

#719 More wound allocation!
  src/army/beasts_of_chaos/allegiances.ts
  src/army/cities_of_sigmar/units.ts
  src/army/daughters_of_khaine/artifacts.ts
  src/army/everchosen/units.ts
  src/army/generic/endless_spells.ts
  src/army/generic/realm_artifacts.ts
  src/army/gloomspite/units.ts
  src/army/grand_alliances/death/artifacts.ts
  src/army/khorne/units.ts
  src/army/nurgle/artifacts.ts
  src/army/ossiarch_bonereapers/allegiances.ts
  src/army/skaven/spells.ts
  src/army/skaven/units.ts
  src/army/slaves_to_darkness/units.ts
  src/army/stormcast_eternals/artifacts.ts
  src/army/sylvaneth/allegiances.ts
  src/army/sylvaneth/artifacts.ts
  src/army/tomb_kings/units.ts
  src/army/tzeentch/units.ts
Labels: rule updates

#721 Fix name not displayed correctly when ability name is partial match (fixes #718)
  src/components/info/reminder.tsx
  src/tests/processReminders.test.ts
  src/types/data.ts
  src/utils/pdf/generate/generatePdf.ts
  src/utils/processGame.ts
  src/utils/processReminders.ts
  src/utils/textUtils.ts
Labels: bug

#722 Run Prettier on older files
  config-overrides.js
  src/army/big_waaagh/units.ts
  src/components/info/card.tsx
  src/components/info/reminders.tsx
  src/components/input/ally_armies.tsx
  src/components/input/ally_army_builder.tsx
  src/components/input/army_builder.tsx
  src/components/input/getSideEffects.ts
  src/components/input/importPdf/drop_container.tsx
  src/components/input/savedArmies/load_army_btn.tsx
  src/components/input/savedArmies/loaded_army_header.tsx
  src/components/input/savedArmies/save_army_btn.tsx
  src/components/input/shareArmy/share_army_btn.tsx
  src/components/input/toolbar/toolbar.tsx
  src/components/page/homeHeader.tsx
  src/components/print/pdfButton.tsx
  src/components/print/printArmy.tsx
  src/context/useSavedArmies.tsx
  src/ducks/selections.ts
  src/utils/azyr/getAzyrArmy.ts
  src/utils/battlescribe/battlescribeUtils.ts
  src/utils/battlescribe/getters.ts
  src/utils/battlescribe/parseHTML.ts
  src/utils/getArmy/getAllyArmyUnits.ts
  src/utils/getArmy/modify.ts
  src/utils/import/allyData.ts
  src/utils/import/index.ts
  src/utils/mapListToDict.ts
  src/utils/pdf/generate/getVisibleReminders.ts
Labels: maintenance

#728 Skittermob -> Skitterswarm
  package.json
  src/army/gloomspite/units.ts
  src/tests/azyr/getAzyrArmy.test.ts
  src/tests/battlescribe/battlescribeHTML.test.ts
  src/tests/fixtures/azyr/json/Gloomspite2.json
  src/tests/fixtures/battlescribe/html/Nighthaunt4.html
  src/utils/import/options.ts
  yarn.lock
Labels: rule updates

#731 Add ability to gift subscriptions (fixes #645)
  package.json
  src/api/subscriptionApi.ts
  src/components/App.tsx
  src/components/helpers/alreadySubscribed.tsx
  src/components/input/generic_button.tsx
  src/components/input/savedArmies/save_army_btn.tsx
  src/components/input/toolbar/import_army_btn.tsx
  src/components/page/navbar.tsx
  src/components/payment/giftSubscriptions.tsx
  src/components/payment/plans.ts
  src/components/payment/pricingPlans.tsx
  src/components/routes/Profile.tsx
  src/components/routes/Redeem.tsx
  src/components/routes/Subscribe.tsx
  src/context/useSavedArmies.tsx
  src/context/useSubscription.tsx
  src/theme/dark.ts
  src/theme/light.ts
  src/types/subscription.ts
  src/types/theme.ts
  src/utils/analytics.ts
  src/utils/env.ts
  src/utils/handleQueryParams.ts
  src/utils/localStore.ts
  src/utils/subscriptionUtils.ts
  yarn.lock
Labels: enhancement, subscriber feature, ui

#733 Import Fixes
  src/components/routes/Redeem.tsx
  src/tests/battlescribe/battlescribeHTML.test.ts
  src/tests/fixtures/battlescribe/html/Fyreslayers5.html
  src/tests/fixtures/battlescribe/html/Fyreslayers6.html
  src/tests/fixtures/battlescribe/html/Fyreslayers7.html
  src/tests/fixtures/battlescribe/html/Slaanesh3.html
  src/utils/import/options.ts
Labels: battlescribe

#734 Highlight gifted subs
  package.json
  src/components/payment/giftSubscriptions.tsx
  src/components/routes/Home.tsx
  src/css/index.scss
  src/types/subscription.ts
  yarn.lock
Labels: ui

#735 UI and tests
  package.json
  src/army/greenskinz/units.ts
  src/components/input/savedArmies/update_army_btn.tsx
  src/tests/battlescribe/battlescribeHTML.test.ts
  src/tests/fixtures/battlescribe/html/Slaanesh4.html
  src/tests/fixtures/warscroll/json/1573791319612-Warscroll_Builder.json
  src/tests/fixtures/warscroll/json/1573836740544-Warscroll_Builder.json
  src/tests/fixtures/warscroll/json/1573865086310-Warscroll_Builder.json
  src/tests/warscroll/warscrollJson.test.ts
  src/utils/import/options.ts
  yarn.lock
Labels: battlescribe, ui, warscroll-builder

#740 Fix #739
  package.json
  src/army/khorne/spells.ts
  yarn.lock
Labels: rule updates

#743 Errata changes for 11/18
  src/army/legions_of_nagash/units.ts
  src/army/ogor_mawtribes/units.ts
  src/army/ossiarch_bonereapers/spells.ts
  src/army/ossiarch_bonereapers/units.ts
Labels: rule updates

#744 Log individual unit selections
  package.json
  src/army/beasts_of_chaos/index.ts
  src/army/bonesplitterz/index.ts
  src/army/cities_of_sigmar/index.ts
  src/army/daughters_of_khaine/index.ts
  src/army/flesh_eater_courts/index.ts
  src/army/fyreslayers/index.ts
  src/army/idoneth/index.ts
  src/army/ironjawz/index.ts
  src/army/kharadron_overlords/index.ts
  src/army/khorne/index.ts
  src/army/ogor_mawtribes/index.ts
  src/army/ossiarch_bonereapers/index.ts
  src/army/sample_army/index.ts
  src/army/skaven/index.ts
  src/army/skaven/units.ts
  src/army/slaanesh/index.ts
  src/army/soulblight/index.ts
  src/army/stormcast_eternals/index.ts
  src/army/sylvaneth/index.ts
  src/components/info/card.tsx
  src/components/input/ally_army_builder.tsx
  src/components/input/army_builder.tsx
  src/components/input/select.tsx
  src/components/print/pdfButton.tsx
  src/utils/analytics.ts
  yarn.lock
Labels: enhancement, rule updates

#745 Log imports
  src/utils/import/index.ts
Labels: azyr, battlescribe, enhancement, warscroll-builder

#748 Import fixes
  package.json
  src/army/generic/realm_artifacts.ts
  src/tests/azyr/getAzyrArmy.test.ts
  src/tests/fixtures/azyr/json/BigWaaagh2.json
  src/tests/fixtures/azyr/json/Khorne5.json
  src/tests/fixtures/azyr/json/Seraphon2.json
  src/tests/fixtures/warscroll/json/1574207831990-Warscroll_Builder.json
  src/tests/warscroll/warscrollJson.test.ts
  src/utils/azyr/azyrPdf.ts
  src/utils/import/options.ts
  yarn.lock
Labels: azyr, warscroll-builder

#750 Added an XLSX utility for the Honest Wargamer
  package.json
  src/utils/xlsx/exportToSheet.ts
  yarn.lock
Labels: enhancement

#752 Add Vokmortian's Retinue and Kin-eater's Bully Boys battalions
  package.json
  src/army/gloomspite/artifacts.ts
  src/army/ogor_mawtribes/units.ts
  src/army/ossiarch_bonereapers/units.ts
  src/tests/azyr/azyrImport.test.ts
  src/tests/azyr/getAzyrArmy.test.ts
  src/tests/fixtures/azyr/json/Gloomspite3.json
  src/tests/fixtures/azyr/json/KO6.json
  src/tests/fixtures/warscroll/json/1574249013027-Warscroll_Builder.json
  src/tests/fixtures/warscroll/json/1574356951165-Warscroll_Builder.json
  src/tests/fixtures/warscroll/json/1574391649028-Warscroll_Builder.json
  src/tests/warscroll/warscrollJson.test.ts
  src/tests/warscroll/warscrollPdf.test.ts
  src/utils/import/options.ts
  src/utils/warscroll/getWarscrollArmy.ts
  yarn.lock
Labels: azyr, rule updates, warscroll-builder

#753 Mark up and improve display of prayers
  package.json
  src/army/cities_of_sigmar/allegiances.ts
  src/army/cities_of_sigmar/units.ts
  src/army/daughters_of_khaine/spells.ts
  src/army/fyreslayers/spells.ts
  src/army/khorne/endless_spells.ts
  src/army/khorne/spells.ts
  src/army/lethisian_army/spells.ts
  src/army/lethisian_army/units.ts
  src/army/ogor_mawtribes/spells.ts
  src/army/slaves_to_darkness/units.ts
  src/army/stormcast_eternals/spells.ts
  src/components/input/getSideEffects.ts
  src/types/data.ts
  src/utils/getArmy/getCollection.ts
  src/utils/textUtils.ts
  yarn.lock
Labels: enhancement, rule updates

#754 Fix spelling of Phoenix Stone
  src/army/grand_alliances/order/artifacts.ts
Labels: rule updates

#762 Add Realm of Origin (fixes #727)
  package.json
  src/army/tamurkhans_horde/units.ts
  src/components/App.tsx
  src/components/info/card.tsx
  src/components/input/army_builder.tsx
  src/components/input/army_builder_cards.ts
  src/components/input/importPdf/drop_container.tsx
  src/components/input/savedArmies/load_army_btn.tsx
  src/components/input/savedArmies/saved_army_table.tsx
  src/components/payment/pricingPlans.tsx
  src/context/useSavedArmies.tsx
  src/ducks/realmscape.ts
  src/ducks/selectors.ts
  src/tests/azyr/getAzyrArmy.test.ts
  src/tests/battlescribe/battlescribeHTML.test.ts
  src/tests/fixtures/battlescribe/html/BCR1.html
  src/tests/fixtures/battlescribe/html/GHoN3.html
  src/tests/fixtures/warscroll/json/1574746733739-Warscroll_Builder.json
  src/tests/processReminders.test.ts
  src/tests/warscroll/warscrollJson.test.ts
  src/tests/warscroll/warscrollPdf.test.ts
  src/types/army.ts
  src/types/import.ts
  src/types/realmscapes.ts
  src/types/store.ts
  src/utils/armyUtils.ts
  src/utils/azyr/getAzyrArmy.ts
  src/utils/battlescribe/checks.ts
  src/utils/battlescribe/getBattlescribeArmy.ts
  src/utils/battlescribe/getters.ts
  src/utils/battlescribe/parseHTML.ts
  src/utils/getArmy/getArmy.ts
  src/utils/getArmy/modify.ts
  src/utils/handleQueryParams.ts
  src/utils/import/options.ts
  src/utils/loadArmyFromLocalStore.ts
  src/utils/loadArmyHelpers.ts
  src/utils/realmUtils.ts
  src/utils/warscroll/getWarscrollArmy.ts
  yarn.lock
Labels: enhancement, ui

#763 Improve mobile styling of realm dropdowns
  src/components/info/card.tsx
  src/components/input/army_builder.tsx
  src/components/input/army_builder_cards.ts
Labels: ui

#765 March of the Dead: start of hero phase (fixes #764)
  README.md
  package.json
  src/army/legions_of_nagash/units.ts
  yarn.lock
Labels: rule updates

#766 Better tracking
  package.json
  src/components/App.tsx
  src/components/input/importPdf/drop_container.tsx
  src/components/input/savedArmies/load_army_btn.tsx
  src/types/import.ts
  src/utils/handleQueryParams.ts
  src/utils/import/index.ts
  src/utils/loadArmy/loadArmyHelpers.ts
  src/utils/loadArmy/logLoadedArmy.ts
  yarn.lock
Labels: enhancement

#767 Fix duplicate tracking
  src/components/page/navbar.tsx
  src/components/payment/giftSubscriptions.tsx
  src/components/payment/pricingPlans.tsx
  src/tests/azyr/azyrImport.test.ts
  src/tests/azyr/getAzyrArmy.test.ts
  src/tests/warscroll/warscrollJson.test.ts
  src/tests/warscroll/warscrollPdf.test.ts
  src/utils/analytics.ts
  src/utils/import/index.ts
  src/utils/loadArmy/loadArmyHelpers.ts
  src/utils/loadArmy/logLoadedArmy.ts
  src/utils/plans.ts
Labels: bug

#770 Update Freeguild rules (fixes #769)
  src/army/cities_of_sigmar/units.ts
Labels: rule updates

#771 Add side effects to dropdown on import
  src/army/cities_of_sigmar/units.ts
  src/army/seraphon/units.ts
  src/components/input/army_builder_cards.ts
  src/tests/azyr/getAzyrArmy.test.ts
  src/tests/battlescribe/battlescribeHTML.test.ts
  src/tests/warscroll/warscrollJson.test.ts
  src/tests/warscroll/warscrollPdf.test.ts
  src/utils/analytics.ts
  src/utils/getSideEffects.ts
  src/utils/import/addSideEffectsToImport.ts
  src/utils/import/index.ts
Labels: azyr, battlescribe, enhancement, warscroll-builder

#775 Better tracking, part two
  src/army/grand_host_of_nagash/artifacts.ts
  src/components/info/card.tsx
  src/components/input/ally_army_builder.tsx
  src/components/input/army_builder.tsx
  src/components/input/select.tsx
  src/utils/analytics.ts
  src/utils/getSideEffects.ts
  src/utils/withSelect.ts
Labels: maintenance, rule updates

#776 Battlemage split (Fixes #551)
  src/army/cities_of_sigmar/units.ts
  src/tests/warscroll/warscrollJson.test.ts
  src/tests/warscroll/warscrollPdf.test.ts
  src/utils/warscroll/getWarscrollArmy.ts
Labels: rule updates

#777 Rules cleanup
  src/army/big_waaagh/spells.ts
  src/army/cities_of_sigmar/units.ts
  src/army/grand_host_of_nagash/artifacts.ts
  src/army/legions_of_nagash/abilities.ts
  src/army/legions_of_nagash/artifacts.ts
  src/army/legions_of_nagash/endless_spells.ts
  src/army/legions_of_nagash/index.ts
  src/army/legions_of_nagash/traits.ts
  src/army/tomb_kings/units.ts
Labels: rule updates
