Repository daviseford/aos-reminders, pull requests merged in 2020-06, with the labels that each got.

#945 Update Typescript, Stripe, and auth0
  package.json
  yarn.lock
Labels: maintenance

#952 Imports and deps
  package.json
  src/army/big_waaagh/abilities.ts
  src/army/daughters_of_khaine/units.ts
  src/army/kharadron_overlords/allegiances.ts
  src/tests/battlescribe/battlescribeHTML.test.ts
  src/tests/fixtures/battlescribe/html/1590913977244-Battlescribe.html
  src/tests/fixtures/warscroll/json/1591871273929-Warscroll_Builder.json
  src/tests/fixtures/warscroll/json/1592153855214-Warscroll_Builder.json
  src/tests/fixtures/warscroll/json/1592258767793-Warscroll_Builder.json
  src/tests/warscroll/warscrollJson.test.ts
  src/utils/import/options.ts
  yarn.lock
Labels: azyr, battlescribe, maintenance, rule updates, warscroll-builder

#962 Fix weird duplicated Infernal Flames
  src/army/slaves_to_darkness/units.ts
  src/army/tzeentch/units.ts
Labels: rule updates

#964 Move FEC warscroll spells to the right place
  src/army/flesh_eater_courts/spells.ts
  src/army/flesh_eater_courts/units.ts
  src/tests/azyr/getAzyrArmy.test.ts
Labels: rule updates

#963 Make all the Spider Venom rules correct
  src/army/gloomspite/units.ts
Labels: rule updates

#961 Update wording of Sorcerous Elixir ability
  src/army/beasts_of_chaos/units.ts
Labels: rule updates

#959 Remove Slann and Kroak spells from spells.ts
  src/army/seraphon/spells.ts
  src/tests/battlescribe/battlescribeHTML.test.ts
Labels: rule updates

#960 Make reordering and hiding play nicely together
  src/components/info/reminders.tsx
  src/utils/reorder.ts
Labels: bug, enhancement

#966 Fix a couple of visual bugs on modals
  src/components/info/confirm_dismiss_notification_modal.tsx
  src/components/input/savedArmies/delete_army_modal.tsx
Labels: ui
