Repository daviseford/aos-reminders, pull requests merged in 2020-12, with the labels that each got.

#1087 Move reminder dropdown back onto title row on mobile
  src/components/info/reminder.tsx
Labels: ui

#1135 v4: Finish Ogor mawtribes
  src/components/print/printArmy.tsx
  src/ducks/army.ts
  src/ducks/selections.ts
  src/factions/ogor_mawtribes/battalions.ts
  src/factions/ogor_mawtribes/command_abilities.ts
  src/factions/ogor_mawtribes/command_traits.ts
  src/factions/ogor_mawtribes/endless_spells.ts
  src/factions/ogor_mawtribes/mount_traits.ts
  src/factions/ogor_mawtribes/spells.ts
  src/factions/ogor_mawtribes/subfactions.ts
  src/factions/ogor_mawtribes/units.ts
  src/factions/sample/command_traits.ts
  src/factions/sample/index.ts
  src/factions/sample/mount_traits.ts
  src/factions/sample/subfactions.ts
  src/tests/__mock.ts
  src/types/army.ts
  src/types/selections.ts
  src/utils/azyr/getAzyrArmy.ts
  src/utils/battlescribe/getters.ts
  src/utils/getArmy/getArmy.ts
  src/utils/getArmy/getCollection.ts
  src/utils/getArmy/modify.ts
  src/utils/getSideEffects.ts
  src/utils/hooks/useGetArmyBuilderCards.tsx
  src/utils/import/removeSideEffectsFromImport.ts
  src/utils/warscroll/getWarscrollArmy.ts
Labels: rule updates

#1137 Fix inheritance issues
  package.json
  src/components/page/homeHeader.tsx
  src/ducks/index.ts
  src/ducks/selections.ts
  src/ducks/selectors.ts
  src/factions/metatagger.ts
  src/utils/analytics.ts
  src/utils/getSideEffects.ts
  src/utils/hooks/useGetArmyBuilderCards.tsx
  src/utils/withSelect.ts
  yarn.lock
Labels: bug
