Repository daviseford/aos-reminders, pull requests merged in 2020-01, with the labels that each got.

#822 Stop logging duplicate individual selections
  src/components/input/importPdf/drop_zone.tsx
  src/components/input/savedArmies/load_army_btn.tsx
  src/components/page/homeHeader.tsx
  src/utils/analytics.ts
  yarn.lock
Labels: bug

#826 Various rule fixes
  package.json
  src/army/khorne/endless_spells.ts
  src/army/seraphon/units.ts
  src/army/sylvaneth/units.ts
  yarn.lock
Labels: rule updates

#827 Re-add Dispossessed
  src/army/dispossessed/abilities.ts
  src/army/dispossessed/artifacts.ts
  src/army/dispossessed/index.ts
  src/army/dispossessed/traits.ts
  src/army/dispossessed/units.ts
  src/meta/army_list.ts
  src/meta/factions.ts
  src/tests/azyr/azyrImport.test.ts
  src/tests/fixtures/azyr/json/Dispossessed1.json
  src/utils/import/options.ts
Labels: new army

#829 Remove Mercenary Companies from the primary faction selection
  package.json
  src/components/page/homeHeader.tsx
  src/components/routes/Profile.tsx
  src/meta/factions.ts
  src/tests/fixtures/warscroll/json/1577866703167-Warscroll_Builder.json
  src/tests/warscroll/warscrollJson.test.ts
  src/utils/import/options.ts
Labels: ui, warscroll-builder

#837 Alphabetize Reminders by Unit Name
  package.json
  src/utils/processReminders.ts
  yarn.lock
Labels: ui

#835 Remove 'Shock and Awe' from shooting phase
  src/army/stormcast_eternals/abilities.ts
Labels: rule updates

#845 Import fixes
  package.json
  src/army/khorne/artifacts.ts
  src/tests/azyr/getAzyrArmy.test.ts
  src/tests/battlescribe/battlescribeHTML.test.ts
  src/tests/fixtures/azyr/json/StD11.json
  src/tests/fixtures/azyr/json/Stormcast7.json
  src/tests/fixtures/azyr/json/Tzeentch3.json
  src/tests/fixtures/battlescribe/html/LoG2.html
  src/tests/fixtures/battlescribe/html/OBR1.html
  src/tests/fixtures/battlescribe/html/OBR2.html
  src/tests/fixtures/battlescribe/html/Stormcast7.html
  src/tests/fixtures/battlescribe/html/Tzeentch3.html
  src/tests/fixtures/warscroll/json/1578184338167-Warscroll_Builder.json
  src/tests/fixtures/warscroll/json/1578192442310-Warscroll_Builder.json
  src/tests/fixtures/warscroll/json/1578518862312-Warscroll_Builder.json
  src/tests/fixtures/warscroll/json/1578691480138-Warscroll_Builder.json
  src/tests/fixtures/warscroll/json/1578730417865-Warscroll_Builder.json
  src/tests/warscroll/warscrollJson.test.ts
  src/utils/azyr/azyrPdf.ts
  src/utils/battlescribe/checks.ts
  src/utils/battlescribe/getters.ts
  src/utils/battlescribe/parseHTML.ts
  src/utils/import/options.ts
  yarn.lock
Labels: azyr, battlescribe, warscroll-builder

#846 Update slaves
  src/army/slaves_to_darkness/abilities.ts
  src/army/slaves_to_darkness/allegiances.ts
  src/army/slaves_to_darkness/units.ts
Labels: rule updates

#839 Tzeentch updates (fixes #834)
  src/army/beasts_of_chaos/units.ts
  src/army/tzeentch/abilities.ts
  src/army/tzeentch/allegiances.ts
  src/army/tzeentch/artifacts.ts
  src/army/tzeentch/endless_spells.ts
  src/army/tzeentch/index.ts
  src/army/tzeentch/spells.ts
  src/army/tzeentch/traits.ts
  src/army/tzeentch/units.ts
  yarn.lock
Labels: new army, rule updates

#847 Fix tests, add Skink Alpha
  package.json
  src/army/seraphon/units.ts
  src/tests/azyr/getAzyrArmy.test.ts
  src/tests/battlescribe/battlescribeHTML.test.ts
  src/tests/warscroll/warscrollJson.test.ts
  yarn.lock
Labels: rule updates

#850 Typo fixes (fixes #848)
  src/army/tzeentch/abilities.ts
  src/army/tzeentch/allegiances.ts
  src/army/tzeentch/units.ts
Labels: rule updates

#853 Import fixes
  src/army/generic/realm_artifacts.ts
  src/tests/azyr/getAzyrArmy.test.ts
  src/tests/battlescribe/battlescribeHTML.test.ts
  src/tests/fixtures/azyr/json/IDK4.json
  src/tests/fixtures/azyr/json/Slaanesh4.json
  src/tests/fixtures/azyr/json/Tzeentch4.json
  src/tests/fixtures/battlescribe/html/OBR3.html
  src/tests/fixtures/battlescribe/html/OBR4.html
  src/tests/fixtures/battlescribe/html/StD4.html
  src/tests/fixtures/warscroll/json/1579105159803-Warscroll_Builder.json
  src/tests/warscroll/warscrollJson.test.ts
  src/tests/warscroll/warscrollPdf.test.ts
  src/utils/azyr/azyrPdf.ts
  src/utils/battlescribe/battlescribeUtils.ts
  src/utils/getArmy/getAllianceItems.ts
  src/utils/getArmy/getArmy.ts
  src/utils/import/options.ts
Labels: azyr, battlescribe, warscroll-builder

#854 Update Typescript, add Stormvermin rules, add release notes to footer
  package.json
  src/army/skaven/units.ts
  src/components/page/footer.tsx
  yarn.lock
Labels: rule updates

#855 Add AoS Shorts xlsx option
  src/types/army.ts
  src/utils/dev/exportToSheet.ts
Labels: maintenance

#858 KO Rules fix
  package.json
  src/army/kharadron_overlords/units.ts
  yarn.lock
Labels: rule updates

#859 Import fixes for KO
  src/army/grand_alliances/order/units.ts
  src/army/kharadron_overlords/allegiances.ts
  src/army/kharadron_overlords/artifacts.ts
  src/army/kharadron_overlords/traits.ts
  src/army/stormcast_eternals/artifacts.ts
  src/army/tzeentch/allegiances.ts
  src/tests/azyr/getAzyrArmy.test.ts
  src/tests/fixtures/azyr/json/KO10.json
  src/tests/fixtures/azyr/json/KO9.json
  src/tests/fixtures/azyr/json/Tzeentch5.json
  src/utils/azyr/azyrPdf.ts
Labels: azyr

#860 Brutefist fix per AoS Shorts
  package.json
  src/utils/import/options.ts
  yarn.lock
Labels: warscroll-builder

#861 Add Stats portal for subscribers (fixes #851)
  package.json
  public/img/aos-reminders.png
  public/img/logo.png
  public/img/logo_border.png
  public/img/logo_medium_padding.png
  public/img/logo_more_padding.png
  public/img/logo_noURL.png
  public/img/logo_square.png
  public/img/stats_cta_desktop.png
  public/img/stats_cta_mobile.png
  public/img/stats_demo_desktop.png
  public/img/stats_demo_mobile.png
  public/img/transparent-with-padding.png
  src/components/App.tsx
  src/components/info/banners/app_banner.tsx
  src/components/page/navbar.tsx
  src/components/routes/Stats.tsx
  src/components/routes/Subscribe.tsx
  src/css/index.scss
  src/utils/env.ts
  src/utils/mapSizesToProps.ts
  src/utils/plans.ts
  yarn.lock
Labels: enhancement, subscriber feature

#862 Update azyrPdf.ts
  src/utils/azyr/azyrPdf.ts
Labels: azyr
