Repository daviseford/aos-reminders, pull requests merged in 2020-03, with the labels that each got.

#898 Re-add Drag and Drop (fixed state bug)
  package.json
  src/army/stormcast_eternals/units.ts
  src/components/info/reminder.tsx
  src/tests/utils.test.ts
  src/types/data.ts
  src/types/pdf.ts
  src/types/store.ts
  src/utils/processGame.ts
  src/utils/processReminders.ts
  src/utils/reminderUtils.ts
  src/utils/textUtils.ts
  yarn.lock
Labels: ui

#900 Drag and Drop improvements
  src/army/seraphon/units.ts
  src/components/info/reminder.tsx
  src/utils/localStore.ts
  src/utils/pdf/generate/layouts/compact.ts
  src/utils/pdf/generate/layouts/default.ts
  src/utils/pdf/generate/layouts/layoutUtils.ts
  src/utils/reorder.ts
Labels: pdf, ui

#905 Updated Chaos files to add information and improve readability/flow.
  src/army/khorne/abilities.ts
  src/army/khorne/spells.ts
  src/army/khorne/units.ts
  src/army/nurgle/abilities.ts
  src/army/nurgle/spells.ts
  src/army/nurgle/units.ts
  src/army/slaanesh/abilities.ts
  src/army/slaanesh/spells.ts
  src/army/slaanesh/units.ts
  src/army/tzeentch/abilities.ts
  src/army/tzeentch/spells.ts
  src/army/tzeentch/units.ts
Labels: rule updates

#915 New Seraphon Battletome (fixes #904)
  package.json
  src/army/seraphon/abilities.ts
  src/army/seraphon/allegiances.ts
  src/army/seraphon/artifacts.ts
  src/army/seraphon/index.ts
  src/army/seraphon/scenery.ts
  src/army/seraphon/spells.ts
  src/army/seraphon/traits.ts
  src/army/seraphon/units.ts
  src/tests/azyr/getAzyrArmy.test.ts
  src/tests/battlescribe/battlescribeHTML.test.ts
  src/tests/getArmy.test.ts
  src/tests/warscroll/warscrollJson.test.ts
  src/tests/warscroll/warscrollPdf.test.ts
  src/utils/import/options.ts
Labels: rule updates

#917 Update dependencies
  .prettierignore
  .prettierrc
  package.json
  src/components/payment/giftSubscriptions.tsx
  src/components/payment/pricingPlans.tsx
  src/components/print/pdfModal.tsx
  src/context/useAppStatus.tsx
  src/utils/azyr/azyrPdf.ts
  src/utils/battlescribe/getters.ts
  src/utils/import/ambiguousSelections.ts
  src/utils/import/index.ts
  src/utils/pdf/generate/layouts/default.ts
  src/utils/textUtils.ts
  src/utils/warscroll/getWarscrollArmy.ts
  yarn.lock
Labels: maintenance

#918 Fix small typo in rules for Horticulus Slimux's Beast Handler ability
  src/army/nurgle/units.ts
Labels: rule updates

#919 Update pdf.js and add new contributor
  README.md
  package.json
  yarn.lock
Labels: maintenance

#926 Seraphon FAQ
  package.json
  src/army/seraphon/abilities.ts
  src/army/seraphon/allegiances.ts
  src/army/seraphon/endless_spells.ts
  src/army/seraphon/units.ts
  src/army/slaves_to_darkness/allegiances.ts
  yarn.lock
Labels: rule updates
