Repository daviseford/aos-reminders, pull requests merged in 2020-10, with the labels that each got.

#1034 Remove email verification UI
  package.json
  src/components/routes/Profile.tsx
  yarn.lock
Labels: ui

#1038 Add Azyr warning about Saurus Scar-Veteran
  package.json
  src/tests/azyr/getAzyrArmy.test.ts
  src/tests/fixtures/azyr/json/ScarVeteran.json
  src/utils/import/options.ts
  yarn.lock
Labels: azyr, rule updates

#1040 Add new Warcry Warbands
  src/army/daughters_of_khaine/units.ts
  src/army/slaves_to_darkness/units.ts
Labels: rule updates

#1049 Update IronJawz to reflect most recent errata
  src/army/ironjawz/units.ts
Labels: rule updates

#1051 Rule updates.
  src/army/daughters_of_khaine/units.ts
  src/army/khorne/endless_spells.ts
Labels: rule updates

#1052 Add Da Bossfist battalion to Ironjawz
  package.json
  src/army/ironjawz/allegiances.ts
  src/army/ironjawz/units.ts
  src/tests/battlescribe/battlescribeHTML.test.ts
  src/utils/import/options.ts
  yarn.lock
Labels: rule updates

#1058 Add White Dwarf content and import fixes for Azyr, WSB, and Battlescribe
  src/army/gloomspite_gitz/allegiances.ts
  src/army/gloomspite_gitz/scenery.ts
  src/army/gloomspite_gitz/units.ts
  src/army/lumineth_realmlords/spells.ts
  src/tests/azyr/getAzyrArmy.test.ts
  src/tests/battlescribe/battlescribeHTML.test.ts
  src/tests/fixtures/azyr/json/1602264690883-Azyr.json
  src/tests/fixtures/battlescribe/html/1601345187171-Battlescribe.html
  src/tests/fixtures/battlescribe/html/1601408881720-Battlescribe.html
  src/tests/fixtures/battlescribe/html/1601411067591-Battlescribe.html
  src/tests/fixtures/battlescribe/html/1602294536060-Battlescribe.html
  src/tests/fixtures/battlescribe/html/1602294559289-Battlescribe.html
  src/tests/fixtures/battlescribe/html/1602790654401-Battlescribe.html
  src/tests/fixtures/battlescribe/html/1603428388643-Battlescribe.html
  src/tests/fixtures/battlescribe/html/1603737835449-Battlescribe.html
  src/tests/fixtures/warscroll/json/1572043447588-Warscroll_Builder.json
  src/tests/fixtures/warscroll/json/1579105159803-Warscroll_Builder.json
  src/tests/fixtures/warscroll/json/1601977490829-Warscroll_Builder.json
  src/tests/fixtures/warscroll/json/1603491054480-Warscroll_Builder.json
  src/tests/fixtures/warscroll/json/1603703587229-Warscroll_Builder.json
  src/tests/warscroll/warscrollJson.test.ts
  src/utils/battlescribe/getters.ts
  src/utils/import/options.ts
Labels: azyr, battlescribe, rule updates, warscroll-builder
