Repository daviseford/aos-reminders, pull requests merged in 2020-02, with the labels that each got.

#867 Log parent army to analytics when an allied unit or battalion is taken (fixes #866)
  package.json
  src/components/input/ally_army_builder.tsx
  src/components/routes/Stats.tsx
  yarn.lock
Labels: maintenance

#869 Tzeentch FAQ (fixes #868)
  src/army/tzeentch/abilities.ts
  src/army/tzeentch/units.ts
Labels: rule updates

#871 Tweak Black Coach rules
  src/army/nighthaunt/units.ts
Labels: rule updates

#873 Add Summon Starlight (fixes #872)
  package.json
  src/army/seraphon/units.ts
  src/tests/warscroll/warscrollPdf.test.ts
  yarn.lock
Labels: rule updates

#875 Update Starbucklers phase (fixes #874)
  src/army/seraphon/units.ts
Labels: rule updates

#878 Import fixes post-Everchosen
  package.json
  src/army/legion_of_chaos_ascendant/units.ts
  src/tests/azyr/getAzyrArmy.test.ts
  src/tests/battlescribe/battlescribeHTML.test.ts
  src/tests/fixtures/azyr/json/KO11.json
  src/tests/fixtures/azyr/json/KO12.json
  src/tests/fixtures/azyr/json/KO13.json
  src/tests/fixtures/azyr/json/KO14.json
  src/tests/fixtures/azyr/json/KO15.json
  src/tests/fixtures/azyr/json/KO16.json
  src/tests/fixtures/azyr/json/KO17.json
  src/tests/fixtures/azyr/json/KO9.json
  src/tests/fixtures/azyr/json/Nurgle4.json
  src/tests/fixtures/warscroll/json/1580248993240-Warscroll_Builder.json
  src/tests/fixtures/warscroll/json/1580490187686-Warscroll_Builder.json
  src/tests/fixtures/warscroll/json/1580985291764-Warscroll_Builder.json
  src/tests/fixtures/warscroll/json/1581087249822-Warscroll_Builder.json
  src/tests/fixtures/warscroll/json/1581111836908-Warscroll_Builder.json
  src/tests/fixtures/warscroll/json/1581135844634-Warscroll_Builder.json
  src/tests/fixtures/warscroll/json/1581363713665-Warscroll_Builder.json
  src/tests/warscroll/warscrollJson.test.ts
  src/tests/warscroll/warscrollPdf.test.ts
  src/utils/azyr/azyrPdf.ts
  src/utils/import/options.ts
  src/utils/warscroll/getWarscrollArmy.ts
Labels: azyr, warscroll-builder

#879 Fixed typo in Tzeentch abilities
  src/army/tzeentch/abilities.ts
Labels: rule updates

#880 More import fixes
  package.json
  src/army/gloomspite/spells.ts
  src/army/kharadron_overlords/units.ts
  src/army/nurgle/units.ts
  src/army/seraphon/units.ts
  src/army/tzeentch/abilities.ts
  src/components/routes/Home.tsx
  src/tests/battlescribe/battlescribeHTML.test.ts
  src/tests/fixtures/battlescribe/html/Gloomspite5.html
  src/tests/fixtures/battlescribe/html/Khorne7.html
  src/tests/fixtures/battlescribe/html/Nighthaunt6.html
  src/tests/fixtures/battlescribe/html/Nurgle4.html
  src/tests/fixtures/battlescribe/html/Slaanesh5.html
  src/tests/fixtures/battlescribe/html/StD5.html
  src/tests/fixtures/battlescribe/html/StD6.html
  src/tests/fixtures/battlescribe/html/Tzeentch4.html
  src/tests/fixtures/warscroll/json/1581426257666-Warscroll_Builder.json
  src/tests/fixtures/warscroll/json/1581436593161-Warscroll_Builder.json
  src/tests/fixtures/warscroll/json/1581503416759-Warscroll_Builder.json
  src/tests/warscroll/warscrollJson.test.ts
  src/utils/import/options.ts
  yarn.lock
Labels: azyr, battlescribe, rule updates, warscroll-builder

#882 Add Aeon Shield to Saurus Sunblood #881
  package.json
  src/army/seraphon/units.ts
  yarn.lock
Labels: rule updates

#886 ADD .nvmrc which is used by nvm to set the node version
  .nvmrc
Labels: maintenance

#887 Sort by action title
  src/components/info/reminder.tsx
  src/components/info/reminders.tsx
  src/types/data.ts
  src/utils/processReminders.ts
Labels: ui

#894 Migrate to new stripe library, Seraphon rules updates, Geminids errata
  README.md
  package.json
  src/army/generic/endless_spells.ts
  src/army/seraphon/units.ts
  src/components/payment/asyncStripeProvider.tsx
  src/components/payment/giftSubscriptions.tsx
  src/components/payment/pricingPlans.tsx
  yarn.lock
Labels: maintenance, rule updates

#895 More Seraphon rule updates
  src/army/seraphon/units.ts
Labels: rule updates

#896 Add Drag and Drop
  package.json
  src/army/stormcast_eternals/units.ts
  src/components/info/reminder.tsx
  src/tests/utils.test.ts
  src/types/data.ts
  src/types/pdf.ts
  src/types/store.ts
  src/utils/processGame.ts
  src/utils/processReminders.ts
  src/utils/reminderUtils.ts
  src/utils/textUtils.ts
  yarn.lock
Labels: ui
