Repository daviseford/aos-reminders, pull requests merged in 2021-04, with the labels that each got.

#1250 Broken Realms: Teclis
  clean.js
  src/factions/cities_of_sigmar/artifacts.ts
  src/factions/cities_of_sigmar/battalions.ts
  src/factions/cities_of_sigmar/command_abilities.ts
  src/factions/cities_of_sigmar/command_traits.ts
  src/factions/cities_of_sigmar/flavors.ts
  src/factions/cities_of_sigmar/spells.ts
  src/factions/cities_of_sigmar/subfactions.ts
  src/factions/flesh_eater_courts/battalions.ts
  src/factions/flesh_eater_courts/command_traits.ts
  src/factions/idoneth_deepkin/battalions.ts
  src/factions/lumineth_realmlords/artifacts.ts
  src/factions/lumineth_realmlords/battalions.ts
  src/factions/lumineth_realmlords/battle_traits.ts
  src/factions/lumineth_realmlords/command_abilities.ts
  src/factions/lumineth_realmlords/command_traits.ts
  src/factions/lumineth_realmlords/flavors.ts
  src/factions/lumineth_realmlords/scenery.ts
  src/factions/lumineth_realmlords/spells.ts
  src/factions/lumineth_realmlords/subfactions.ts
  src/factions/lumineth_realmlords/units.ts
  src/factions/nurgle/battalions.ts
  src/factions/nurgle/command_traits.ts
  src/factions/nurgle/units.ts
  src/factions/ossiarch_bonereapers/battalions.ts
  src/factions/stormcast_eternals/battalions.ts
  src/generic_rules/realmscape_artifacts.ts
  src/generic_rules/realmscape_commands.ts
  src/generic_rules/realmscape_features.ts
  src/generic_rules/realmscape_spells.ts
  src/tests/azyr/getAzyrArmy.test.ts
  src/tests/warscroll/warscrollPdf.test.ts
  src/types/realmscapes.ts
Labels: rule updates

#1251 Add error logging and try to prevent failure on invalid Faction names
  package.json
  src/components/info/reminder.tsx
  src/components/input/savedArmies/saved_army_table.tsx
  src/components/modals/paypal_cancellation_modal.tsx
  src/components/modals/stripe_cancellation_modal.tsx
  src/components/page/homeHeader.tsx
  src/context/useSavedArmies.tsx
  src/meta/faction_list.ts
  src/store/index.tsx
  src/types/data.ts
  src/utils/analytics.ts
  src/utils/import/checkErrors.ts
  src/utils/localStore.ts
  yarn.lock
Labels: bug

#1253 Fixes issue #1252
  src/factions/nighthaunt/units.ts
Labels: rule updates

#1254 Update workbox
  package.json
  yarn.lock
Labels: maintenance

#1259 Update yarn.lock
  package.json
  yarn.lock
Labels: maintenance

#1267 Update dependencies
  package.json
  yarn.lock
Labels: maintenance
