Repository daviseford/aos-reminders, pull requests merged in 2021-05, with the labels that each got.

#1270 Update auth0, stripe, core-js
  package.json
  src/components/payment/giftSubscriptions.tsx
  src/components/payment/paypal/paypalButton.tsx
  src/components/payment/pricingPlans.tsx
  src/components/routes/Join.tsx
  src/components/routes/Profile.tsx
  src/components/routes/Redeem.tsx
  src/context/useSavedArmies.tsx
  src/context/useSubscription.tsx
  yarn.lock
Labels: dependencies

#1212 Add Rules Source
  docs/CONTRIBUTING.md
  package.json
  src/components/info/reminder.tsx
  src/components/info/reminders.tsx
  src/factions/daughters_of_khaine/command_abilities.ts
  src/factions/daughters_of_khaine/command_traits.ts
  src/factions/daughters_of_khaine/index.ts
  src/factions/daughters_of_khaine/rule_sources.ts
  src/factions/factionClass.ts
  src/factions/kharadron_overlords/artifacts.ts
  src/factions/kharadron_overlords/rule_sources.ts
  src/factions/kharadron_overlords/units.ts
  src/factions/mega_gargant_mercenaries/index.ts
  src/factions/mercenary_companies/index.ts
  src/factions/seraphon/battle_traits.ts
  src/factions/seraphon/command_abilities.ts
  src/factions/seraphon/endless_spells.ts
  src/factions/seraphon/index.ts
  src/factions/seraphon/rule_sources.ts
  src/factions/seraphon/spells.ts
  src/factions/slaanesh/battle_traits.ts
  src/factions/slaanesh/index.ts
  src/factions/slaanesh/rule_sources.ts
  src/factions/sons_of_behemat/artifacts.ts
  src/factions/sons_of_behemat/battle_traits.ts
  src/factions/sons_of_behemat/index.ts
  src/factions/sons_of_behemat/rule_sources.ts
  src/factions/temporaryAdapter.ts
  src/meta/faction_list.ts
  src/meta/rule_sources.ts
  src/meta/sources.ts
  src/types/data.ts
  src/utils/getArmy/getArmy.ts
  src/utils/processGame.ts
Labels: enhancement, help wanted

#1271 Fix units dropdown being badly populated
  src/factions/daughters_of_khaine/command_traits.ts
  src/factions/kharadron_overlords/units.ts
  src/factions/seraphon/battle_traits.ts
  src/factions/seraphon/command_abilities.ts
  src/factions/seraphon/index.ts
  src/factions/seraphon/spells.ts
  src/factions/slaanesh/battle_traits.ts
  src/tests/azyr/getAzyrArmy.test.ts
  src/tests/getArmy.test.ts
  src/utils/getArmy/getCollection.ts
Labels: bug

#1274 Add May FAQs
  package.json
  src/factions/lumineth_realmlords/command_abilities.ts
  src/factions/lumineth_realmlords/command_traits.ts
  src/factions/lumineth_realmlords/index.ts
  src/factions/lumineth_realmlords/rule_sources.ts
  src/factions/lumineth_realmlords/spells.ts
  src/factions/lumineth_realmlords/units.ts
  src/meta/rule_sources.ts
  yarn.lock
Labels: dependencies, rule updates

#1275 Adding more rule sources
  package.json
  src/factions/flesh_eater_courts/artifacts.ts
  src/factions/flesh_eater_courts/command_abilities.ts
  src/factions/flesh_eater_courts/command_traits.ts
  src/factions/flesh_eater_courts/endless_spells.ts
  src/factions/flesh_eater_courts/index.ts
  src/factions/flesh_eater_courts/rule_sources.ts
  src/factions/flesh_eater_courts/scenery.ts
  src/factions/kharadron_overlords/artifacts.ts
  src/factions/kharadron_overlords/rule_sources.ts
  src/factions/kharadron_overlords/units.ts
  src/factions/nighthaunt/index.ts
  src/factions/nighthaunt/rule_sources.ts
  src/factions/nighthaunt/spells.ts
  src/factions/seraphon/battle_traits.ts
  src/factions/seraphon/command_abilities.ts
  src/factions/seraphon/endless_spells.ts
  src/factions/seraphon/rule_sources.ts
  src/factions/seraphon/spells.ts
  src/factions/slaves_to_darkness/battle_traits.ts
  src/factions/stormcast_eternals/battle_traits.ts
  src/factions/tzeentch/battalions.ts
  src/factions/tzeentch/battle_traits.ts
  src/factions/tzeentch/command_abilities.ts
  src/factions/tzeentch/index.ts
  src/factions/tzeentch/rule_sources.ts
  src/factions/tzeentch/units.ts
  src/meta/rule_sources.ts
  yarn.lock
Labels: rule updates

#1277 Remove favorite faction
  package.json
  src/api/subscriptionApi.ts
  src/components/input/ally_army_builder.tsx
  src/components/input/toolbar/toolbar.tsx
  src/components/page/homeHeader.tsx
  src/components/page/navbar.tsx
  src/components/routes/Profile.tsx
  src/components/routes/Subscribe.tsx
  src/context/useSavedArmies.tsx
  src/context/useSubscription.tsx
  src/store/index.tsx
  src/tests/azyr/getAzyrArmy.test.ts
  src/tests/battlescribe/battlescribeHTML.test.ts
  src/tests/warscroll/warscrollJson.test.ts
  src/utils/analytics.ts
  src/utils/battlescribe/parseHTML.ts
  src/utils/getArmy/getArmy.ts
  src/utils/handleQueryParams.ts
  src/utils/hooks/useGetArmy.tsx
  src/utils/import/selectionLookup.ts
  src/utils/localStore.ts
  src/utils/pdf/generate/generatePdf.ts
  src/utils/pdf/generate/layouts/layoutUtils.ts
  src/utils/withSelect.ts
  yarn.lock
Labels: enhancement, subscriber feature

#1278 Hotfix: Update pricingPlans.tsx
  src/components/payment/pricingPlans.tsx
Labels: bug, subscriber feature

#1281 Adds Cursed City Heroes
  src/factions/cities_of_sigmar/prayers.ts
  src/factions/cities_of_sigmar/spells.ts
  src/factions/cities_of_sigmar/units.ts
  src/factions/kharadron_overlords/units.ts
  src/factions/sylvaneth/units.ts
  src/tests/azyr/getAzyrArmy.test.ts
  src/tests/warscroll/warscrollPdf.test.ts
Labels: rule updates

#1283 Fix StD base effects being duplicated
  package.json
  src/factions/beasts_of_chaos/battle_traits.ts
  src/factions/beasts_of_chaos/subfactions.ts
  src/factions/fyreslayers/battle_traits.ts
  src/factions/fyreslayers/subfactions.ts
  src/factions/gloomspite_gitz/battle_traits.ts
  src/factions/gloomspite_gitz/subfactions.ts
  src/factions/mega_gargant_mercenaries/units.ts
  src/factions/ossiarch_bonereapers/index.ts
  src/factions/ossiarch_bonereapers/subfactions.ts
  src/factions/sample/flavors.ts
  src/factions/sample/index.ts
  src/factions/sample/subfactions.ts
  src/factions/skaventide/index.ts
  src/factions/skaventide/subfactions.ts
  src/factions/slaves_to_darkness/subfactions.ts
  src/factions/sons_of_behemat/battle_traits.ts
  src/factions/sons_of_behemat/flavors.ts
  src/factions/sons_of_behemat/index.ts
  src/factions/sons_of_behemat/subfactions.ts
  src/factions/sons_of_behemat/units.ts
  src/factions/sylvaneth/index.ts
  src/factions/sylvaneth/subfactions.ts
  src/factions/tomb_kings/index.ts
  src/factions/tomb_kings/subfactions.ts
  src/factions/tzeentch/index.ts
  src/factions/tzeentch/subfactions.ts
  src/factions/wanderers/index.ts
  src/factions/wanderers/subfactions.ts
  src/tests/processReminders.test.ts
  yarn.lock
Labels: bug
